<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>161250 Data Analysis - Chapter 7:Models with Multiple Predictors</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">161250 Data Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../slides.html" rel="" target="">
 <span class="menu-text">Slides</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../studyguide/index.html" rel="" target="">
 <span class="menu-text">Study Guide</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../workshops/ws01.html" rel="" target="">
 <span class="menu-text">Workshops</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-extra-code" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Extra Code</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-extra-code">    
        <li>
    <a class="dropdown-item" href="../exercises/Chap2more.R" rel="" target="">
 <span class="dropdown-text">Ex2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap3more.R" rel="" target="">
 <span class="dropdown-text">Ex3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap4more.R" rel="" target="">
 <span class="dropdown-text">Ex4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap5more.R" rel="" target="">
 <span class="dropdown-text">Ex5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap6more.R" rel="" target="">
 <span class="dropdown-text">Ex6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap7more.R" rel="" target="">
 <span class="dropdown-text">Ex7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap8more.R" rel="" target="">
 <span class="dropdown-text">Ex8</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives:</a></li>
  <li><a href="#what-is-a-multiple-regression" id="toc-what-is-a-multiple-regression" class="nav-link" data-scroll-target="#what-is-a-multiple-regression">What is a multiple Regression?</a></li>
  <li><a href="#when-to-use-multiple-predictors" id="toc-when-to-use-multiple-predictors" class="nav-link" data-scroll-target="#when-to-use-multiple-predictors">When to use multiple predictors</a></li>
  <li><a href="#multiple-regression" id="toc-multiple-regression" class="nav-link" data-scroll-target="#multiple-regression">Multiple Regression</a></li>
  <li><a href="#data-example" id="toc-data-example" class="nav-link" data-scroll-target="#data-example">Data example</a></li>
  <li><a href="#data-example-1" id="toc-data-example-1" class="nav-link" data-scroll-target="#data-example-1">Data example</a></li>
  <li><a href="#inter-relationships" id="toc-inter-relationships" class="nav-link" data-scroll-target="#inter-relationships">Inter-relationships</a></li>
  <li><a href="#full-regression" id="toc-full-regression" class="nav-link" data-scroll-target="#full-regression">Full regression</a></li>
  <li><a href="#residuals" id="toc-residuals" class="nav-link" data-scroll-target="#residuals">Residuals</a></li>
  <li><a href="#multicollinearity" id="toc-multicollinearity" class="nav-link" data-scroll-target="#multicollinearity">Multicollinearity</a></li>
  <li><a href="#multicollinearity-1" id="toc-multicollinearity-1" class="nav-link" data-scroll-target="#multicollinearity-1">Multicollinearity</a></li>
  <li><a href="#multicollinearity-2" id="toc-multicollinearity-2" class="nav-link" data-scroll-target="#multicollinearity-2">Multicollinearity</a></li>
  <li><a href="#tidy-summary" id="toc-tidy-summary" class="nav-link" data-scroll-target="#tidy-summary">Tidy summary</a></li>
  <li><a href="#model-summary-measures" id="toc-model-summary-measures" class="nav-link" data-scroll-target="#model-summary-measures">Model Summary Measures</a></li>
  <li><a href="#variance-explained" id="toc-variance-explained" class="nav-link" data-scroll-target="#variance-explained">Variance Explained</a></li>
  <li><a href="#variance-explained-1" id="toc-variance-explained-1" class="nav-link" data-scroll-target="#variance-explained-1">Variance Explained</a></li>
  <li><a href="#additional-variation-explained" id="toc-additional-variation-explained" class="nav-link" data-scroll-target="#additional-variation-explained">Additional variation explained</a></li>
  <li><a href="#sequential-addition-of-predictors" id="toc-sequential-addition-of-predictors" class="nav-link" data-scroll-target="#sequential-addition-of-predictors">Sequential addition of predictors</a></li>
  <li><a href="#significance-of-type-i-or-seq.ss" id="toc-significance-of-type-i-or-seq.ss" class="nav-link" data-scroll-target="#significance-of-type-i-or-seq.ss">Significance of Type I or Seq.SS</a></li>
  <li><a href="#type-ii" id="toc-type-ii" class="nav-link" data-scroll-target="#type-ii">Type II</a></li>
  <li><a href="#type-iii-ss" id="toc-type-iii-ss" class="nav-link" data-scroll-target="#type-iii-ss">Type III SS</a></li>
  <li><a href="#ss-types-in-action" id="toc-ss-types-in-action" class="nav-link" data-scroll-target="#ss-types-in-action">SS types in action</a></li>
  <li><a href="#summary-so-far" id="toc-summary-so-far" class="nav-link" data-scroll-target="#summary-so-far">Summary so far</a></li>
  <li><a href="#learning-objectives-1" id="toc-learning-objectives-1" class="nav-link" data-scroll-target="#learning-objectives-1">Learning Objectives:</a></li>
  <li><a href="#does-waffle-houses-cause-divorce" id="toc-does-waffle-houses-cause-divorce" class="nav-link" data-scroll-target="#does-waffle-houses-cause-divorce">Does Waffle Houses cause divorce??</a></li>
  <li><a href="#or-is-it-butter" id="toc-or-is-it-butter" class="nav-link" data-scroll-target="#or-is-it-butter">Or is it butter?</a></li>
  <li><a href="#spurious-association" id="toc-spurious-association" class="nav-link" data-scroll-target="#spurious-association">Spurious association</a></li>
  <li><a href="#how-do-we-deal-with-spurious-associations" id="toc-how-do-we-deal-with-spurious-associations" class="nav-link" data-scroll-target="#how-do-we-deal-with-spurious-associations">How do we deal with spurious associations?</a></li>
  <li><a href="#masked-associations" id="toc-masked-associations" class="nav-link" data-scroll-target="#masked-associations">Masked associations</a></li>
  <li><a href="#masking-situations-tend-to-arise-when" id="toc-masking-situations-tend-to-arise-when" class="nav-link" data-scroll-target="#masking-situations-tend-to-arise-when">Masking situations tend to arise when:</a></li>
  <li><a href="#milk-and-brain-data-example" id="toc-milk-and-brain-data-example" class="nav-link" data-scroll-target="#milk-and-brain-data-example">Milk and brain data example</a></li>
  <li><a href="#primate-milk-data" id="toc-primate-milk-data" class="nav-link" data-scroll-target="#primate-milk-data">Primate milk data</a></li>
  <li><a href="#first-we-will-consider-simple-regressions" id="toc-first-we-will-consider-simple-regressions" class="nav-link" data-scroll-target="#first-we-will-consider-simple-regressions">First we will consider simple regressions</a></li>
  <li><a href="#multiple-regression-1" id="toc-multiple-regression-1" class="nav-link" data-scroll-target="#multiple-regression-1">Multiple regression</a></li>
  <li><a href="#masking-situation" id="toc-masking-situation" class="nav-link" data-scroll-target="#masking-situation">Masking situation</a></li>
  <li><a href="#how-do-we-deal-with-this" id="toc-how-do-we-deal-with-this" class="nav-link" data-scroll-target="#how-do-we-deal-with-this">How do we deal with this?</a></li>
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection">Model Selection</a></li>
  <li><a href="#selection-of-predictors" id="toc-selection-of-predictors" class="nav-link" data-scroll-target="#selection-of-predictors">Selection of predictors</a></li>
  <li><a href="#ockhams-razor" id="toc-ockhams-razor" class="nav-link" data-scroll-target="#ockhams-razor">Ockham’s razor</a></li>
  <li><a href="#overfitting" id="toc-overfitting" class="nav-link" data-scroll-target="#overfitting">Overfitting</a></li>
  <li><a href="#all-possible-models" id="toc-all-possible-models" class="nav-link" data-scroll-target="#all-possible-models">All possible models:</a></li>
  <li><a href="#what-criteria-do-we-use" id="toc-what-criteria-do-we-use" class="nav-link" data-scroll-target="#what-criteria-do-we-use">What criteria do we use?</a></li>
  <li><a href="#when-r2-becomes-absurd" id="toc-when-r2-becomes-absurd" class="nav-link" data-scroll-target="#when-r2-becomes-absurd">When <span class="math inline">\(R^2\)</span> becomes absurd</a></li>
  <li><a href="#model-selection-1" id="toc-model-selection-1" class="nav-link" data-scroll-target="#model-selection-1">Model selection</a></li>
  <li><a href="#model-selection-continued" id="toc-model-selection-continued" class="nav-link" data-scroll-target="#model-selection-continued">Model selection (continued)</a></li>
  <li><a href="#model-selection-continued-1" id="toc-model-selection-continued-1" class="nav-link" data-scroll-target="#model-selection-continued-1">Model selection (continued)</a></li>
  <li><a href="#software" id="toc-software" class="nav-link" data-scroll-target="#software">Software</a></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation">Cross validation</a></li>
  <li><a href="#cross-validated-selection-data-example" id="toc-cross-validated-selection-data-example" class="nav-link" data-scroll-target="#cross-validated-selection-data-example">Cross validated selection: Data example</a></li>
  <li><a href="#cross-validated-selection" id="toc-cross-validated-selection" class="nav-link" data-scroll-target="#cross-validated-selection">Cross validated selection</a></li>
  <li><a href="#polynomial-models" id="toc-polynomial-models" class="nav-link" data-scroll-target="#polynomial-models">Polynomial models</a></li>
  <li><a href="#polynomial-models-data-example" id="toc-polynomial-models-data-example" class="nav-link" data-scroll-target="#polynomial-models-data-example">Polynomial models: Data example</a></li>
  <li><a href="#look-closer" id="toc-look-closer" class="nav-link" data-scroll-target="#look-closer">Look closer</a></li>
  <li><a href="#polynomial-models-data-example-1" id="toc-polynomial-models-data-example-1" class="nav-link" data-scroll-target="#polynomial-models-data-example-1">Polynomial models: Data example</a></li>
  <li><a href="#residual-diagnostics" id="toc-residual-diagnostics" class="nav-link" data-scroll-target="#residual-diagnostics">Residual diagnostics</a></li>
  <li><a href="#categorical-predictors" id="toc-categorical-predictors" class="nav-link" data-scroll-target="#categorical-predictors">Categorical predictors</a></li>
  <li><a href="#indicator-variables" id="toc-indicator-variables" class="nav-link" data-scroll-target="#indicator-variables">Indicator variables</a></li>
  <li><a href="#regression-output" id="toc-regression-output" class="nav-link" data-scroll-target="#regression-output">Regression output</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Chapter07.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Chapter 7:<br>Models with Multiple Predictors</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives:</h2>
<ul>
<li>Understand and describe a multiple linear regression, the difference from a simple linear regression, and when each are appropriate</li>
<li>Fit and display a multiple regression</li>
<li>Understand and interpret different types of Sums of Squares</li>
<li>Understand and test for multicollinearity and other assumptions</li>
</ul>
</section>
<section id="what-is-a-multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="what-is-a-multiple-regression">What is a multiple Regression?</h2>
<ul>
<li>In a simple regression, there is only one predictor.</li>
</ul>
<p>Multiple regression modelling involves many predictors.</p>
</section>
<section id="when-to-use-multiple-predictors" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-multiple-predictors">When to use multiple predictors</h2>
<ul>
<li><p><em>Statistical control of a confound</em>: controlling treatment for some unwanted variability</p></li>
<li><p><em>Multiple causation</em>: multiple things are thought to cause changes in the outcome variable</p></li>
<li><p><em>Interactions</em>: we are interested in how two variables may combine to change our outcome (will cover this in the next chapter)</p></li>
</ul>
</section>
<section id="multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression">Multiple Regression</h2>
<p>Where to start:</p>
<ul>
<li><p>Question and hypothesis + domain knowledge</p>
<ul>
<li>What are we interested in testing?</li>
<li>What data is collected? do those variables make sense?</li>
</ul></li>
<li><p>Perform EDA first</p>
<ul>
<li>A scatter plot matrix can show nonlinear relationships</li>
<li>A correlation matrix will only show the strength of pairwise linear relationships</li>
</ul></li>
<li><p>Look for the predictors having the largest correlation with response</p>
<ul>
<li>Look for inter-correlations between the predictors and choose the one with high correlation with response variable but uncorrelated with the rest.</li>
</ul></li>
</ul>
</section>
<section id="data-example" class="level2">
<h2 class="anchored" data-anchor-id="data-example">Data example</h2>
<p>Basketball team summary for 2020 regular season<br>
</p>
<p>We have 2118 data points which equates to 1059 games (2 teams per game), 2020 was a short season</p>
<p>Each team in a standard season plays 82 games. That means in total, an NBA season is comprised of 1,230 games.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>  Team     Game Spread Outcome MIN PTS       P2p       P3p       FTp OREB DREB
1  ATL 21900014     17       W  48 117 0.6000000 0.3548387 0.8571429    8   34
2  ATL 21900028      4       W  48 103 0.6296296 0.3000000 0.5333333    9   43
3  ATL 21900043     -2       L  48 103 0.4736842 0.3333333 0.6875000    8   37
4  ATL 21900052    -15       L  48  97 0.5454545 0.2820513 0.6666667    9   24
5  ATL 21900066     -9       L  48  97 0.5370370 0.2058824 0.6923077   16   34
6  ATL 21900099      8       W  48 108 0.5333333 0.3666667 0.6875000    9   39
  AST TOV STL BLK PF
1  27  13   9   2 15
2  22  18   5   9 26
3  23  21  12   3 25
4  28  20  14   7 29
5  20  16   5   5 15
6  22  18   9   5 20</code></pre>
</div>
</div>
<p><code>Spread</code>: Point difference between winning and losing team<br>
<code>PTS</code>: Total points scored by a team in a game<br>
<code>P2p</code>: Percent of 2-pointers made<br>
<code>P3p</code>: Percent of 3-pointers made<br>
<code>FTp</code>: Percent of free-throws made<br>
<code>OREB</code>: Offensive rebounds<br>
<code>DREB</code>: Defensive rebounds<br>
<code>AST</code>: Assists<br>
<code>STL</code>: Steals<br>
<code>BLK</code>: Blocks<br>
</p>
</section>
<section id="data-example-1" class="level2">
<h2 class="anchored" data-anchor-id="data-example-1">Data example</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits=</span><span class="dv">3</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(teams[,<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">6</span><span class="sc">:</span><span class="dv">12</span>, <span class="dv">14</span><span class="sc">:</span><span class="dv">15</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Spread     PTS      P2p      P3p     FTp     OREB     DREB     AST
Spread  1.0000  0.5730  0.36338  0.42719  0.1063 -0.00240  0.46470  0.3477
PTS     0.5730  1.0000  0.48713  0.55094  0.1897 -0.01487  0.14131  0.5103
P2p     0.3634  0.4871  1.00000 -0.00601 -0.0105 -0.28585  0.02484  0.3633
P3p     0.4272  0.5509 -0.00601  1.00000  0.0297 -0.18736  0.00164  0.4054
FTp     0.1063  0.1897 -0.01053  0.02967  1.0000 -0.08960 -0.01724 -0.0297
OREB   -0.0024 -0.0149 -0.28585 -0.18736 -0.0896  1.00000  0.03882 -0.0996
DREB    0.4647  0.1413  0.02484  0.00164 -0.0172  0.03882  1.00000  0.0468
AST     0.3477  0.5103  0.36333  0.40540 -0.0297 -0.09960  0.04681  1.0000
STL     0.1246  0.0352  0.01897 -0.04479  0.0115 -0.00389 -0.18027  0.0518
BLK     0.1837  0.0623  0.03757  0.00540 -0.0185  0.00311  0.20700  0.0411
            STL      BLK
Spread  0.12460  0.18367
PTS     0.03525  0.06234
P2p     0.01897  0.03757
P3p    -0.04479  0.00540
FTp     0.01153 -0.01849
OREB   -0.00389  0.00311
DREB   -0.18027  0.20700
AST     0.05178  0.04112
STL     1.00000  0.03267
BLK     0.03267  1.00000</code></pre>
</div>
</div>
</section>
<section id="inter-relationships" class="level2">
<h2 class="anchored" data-anchor-id="inter-relationships">Inter-relationships</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="full-regression" class="level2">
<h2 class="anchored" data-anchor-id="full-regression">Full regression</h2>
<p>Places all of the predictors in the model</p>
<p>Equivalent of throwing everything in and hoping something sticks</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Spread ~ ., data = teams_forlm)

Residuals:
   Min     1Q Median     3Q    Max 
-32.29  -5.72  -0.15   5.66  30.36 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -142.4223     2.8728  -49.58  &lt; 2e-16 ***
PTS            0.0624     0.0269    2.32     0.02 *  
P2p           74.1170     3.8391   19.31  &lt; 2e-16 ***
P3p           74.0109     3.3449   22.13  &lt; 2e-16 ***
FTp           15.4686     2.0265    7.63  3.4e-14 ***
OREB           0.7191     0.0623   11.54  &lt; 2e-16 ***
DREB           1.2033     0.0367   32.81  &lt; 2e-16 ***
AST           -0.0350     0.0479   -0.73     0.47    
STL            1.0685     0.0677   15.79  &lt; 2e-16 ***
BLK            0.3503     0.0784    4.47  8.2e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.79 on 2108 degrees of freedom
Multiple R-squared:  0.622, Adjusted R-squared:  0.62 
F-statistic:  385 on 9 and 2108 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
</section>
<section id="residuals" class="level2">
<h2 class="anchored" data-anchor-id="residuals">Residuals</h2>
<p>Just like with a simple regression we examine residuals to look for patterns</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These look great, probably because we have a ton of data in this example.</p>
</section>
<section id="multicollinearity" class="level2 increment">
<h2 class="increment anchored" data-anchor-id="multicollinearity">Multicollinearity</h2>
<ul>
<li><p><em>Multicollinearity</em> is where at least two predictor variables are highly correlated.</p></li>
<li><p>Multicollinearity does <em>not</em> affect the residual SD very much, and doesn’t pose a major problem for prediction.</p></li>
<li><p>The major effects of multicollinearity are:</p>
<ul>
<li>It changes the estimates of the coefficients.</li>
<li>It inflates the variance of the estimates of the coefficients. That is, it increases the uncertainty about what the slope parameters are.</li>
<li>Therefore, it matters when testing hypotheses about the effects of specific predictors.</li>
</ul></li>
</ul>
</section>
<section id="multicollinearity-1" class="level2">
<h2 class="anchored" data-anchor-id="multicollinearity-1">Multicollinearity</h2>
<ul>
<li><p>The impact of multicollinearity on the variance of the estimates can be quantified using the Variance Inflation Factor (VIF &lt; 5 is considered ok).</p></li>
<li><p>There are several ways to deal with multicollinarity, depending on context. We can discard one of highly correlated variable, perform ridge regression, or think more carefully about how the variables relate to each other.</p></li>
</ul>
</section>
<section id="multicollinearity-2" class="level2">
<h2 class="anchored" data-anchor-id="multicollinearity-2">Multicollinearity</h2>
<p>In R we can examine Multicollinearity using the function <code>vif()</code></p>
<p>Remember our basketball regression:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(full_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> PTS  P2p  P3p  FTp OREB DREB  AST  STL  BLK 
3.07 2.14 2.24 1.14 1.37 1.14 1.50 1.06 1.05 </code></pre>
</div>
</div>
<p>These values are all small (VIF &lt; 5) so we can continue on in interpreting the regression.</p>
</section>
<section id="tidy-summary" class="level2">
<h2 class="anchored" data-anchor-id="tidy-summary">Tidy summary</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="lightable-classic table table-sm table-striped small" data-quarto-postprocess="true">
<caption>t-tests for model parameters</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-142.422</td>
<td style="text-align: right;">2.873</td>
<td style="text-align: right;">-49.575</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">PTS</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">2.320</td>
<td style="text-align: right;">0.020</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P2p</td>
<td style="text-align: right;">74.117</td>
<td style="text-align: right;">3.839</td>
<td style="text-align: right;">19.306</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">P3p</td>
<td style="text-align: right;">74.011</td>
<td style="text-align: right;">3.345</td>
<td style="text-align: right;">22.126</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FTp</td>
<td style="text-align: right;">15.469</td>
<td style="text-align: right;">2.027</td>
<td style="text-align: right;">7.633</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">OREB</td>
<td style="text-align: right;">0.719</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">11.538</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DREB</td>
<td style="text-align: right;">1.203</td>
<td style="text-align: right;">0.037</td>
<td style="text-align: right;">32.809</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AST</td>
<td style="text-align: right;">-0.035</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: right;">-0.729</td>
<td style="text-align: right;">0.466</td>
</tr>
<tr class="odd">
<td style="text-align: left;">STL</td>
<td style="text-align: right;">1.069</td>
<td style="text-align: right;">0.068</td>
<td style="text-align: right;">15.785</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">BLK</td>
<td style="text-align: right;">0.350</td>
<td style="text-align: right;">0.078</td>
<td style="text-align: right;">4.470</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="model-summary-measures" class="level2">
<h2 class="anchored" data-anchor-id="model-summary-measures">Model Summary Measures</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="lightable-classic table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Model summary measures</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">r.squared</td>
<td style="text-align: right;">0.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">sigma</td>
<td style="text-align: right;">8.79</td>
</tr>
<tr class="odd">
<td style="text-align: left;">statistic</td>
<td style="text-align: right;">384.83</td>
</tr>
<tr class="even">
<td style="text-align: left;">p.value</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AIC</td>
<td style="text-align: right;">15227.82</td>
</tr>
<tr class="even">
<td style="text-align: left;">BIC</td>
<td style="text-align: right;">15290.06</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="variance-explained" class="level2">
<h2 class="anchored" data-anchor-id="variance-explained">Variance Explained</h2>
<p><span class="math inline">\(R^2\)</span> is the proportion of variance in <span class="math inline">\(y\)</span> explained by <span class="math inline">\(x\)</span> .</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Spread ~ ., data = teams_forlm)

Residuals:
   Min     1Q Median     3Q    Max 
-32.29  -5.72  -0.15   5.66  30.36 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -142.4223     2.8728  -49.58  &lt; 2e-16 ***
PTS            0.0624     0.0269    2.32     0.02 *  
P2p           74.1170     3.8391   19.31  &lt; 2e-16 ***
P3p           74.0109     3.3449   22.13  &lt; 2e-16 ***
FTp           15.4686     2.0265    7.63  3.4e-14 ***
OREB           0.7191     0.0623   11.54  &lt; 2e-16 ***
DREB           1.2033     0.0367   32.81  &lt; 2e-16 ***
AST           -0.0350     0.0479   -0.73     0.47    
STL            1.0685     0.0677   15.79  &lt; 2e-16 ***
BLK            0.3503     0.0784    4.47  8.2e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.79 on 2108 degrees of freedom
Multiple R-squared:  0.622, Adjusted R-squared:  0.62 
F-statistic:  385 on 9 and 2108 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
</section>
<section id="variance-explained-1" class="level2">
<h2 class="anchored" data-anchor-id="variance-explained-1">Variance Explained</h2>
<p><span class="math inline">\(R^2=\frac{SS~regression}{SS~Total}\)</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>SS <span class="ot">&lt;-</span> <span class="fu">anova</span>(full_reg) <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">tidy</span>() <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term<span class="sc">:</span>sumsq) <span class="sc">|&gt;</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">adorn_totals</span>()</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>SS</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      term   df    sumsq
       PTS    1 141194.6
       P2p    1   4001.7
       P3p    1  14465.4
       FTp    1    583.8
      OREB    1   7082.2
      DREB    1  78359.3
       AST    1     10.1
       STL    1  20082.0
       BLK    1   1542.2
 Residuals 2108 162702.8
     Total 2117 430024.0</code></pre>
</div>
</div>
<ul>
<li><p><span class="math inline">\(R^2_{adj}\)</span> is adjusted to remove the variation that is explained by chance alone</p></li>
<li><p><span class="math inline">\(R^2_{adj}=1-\frac{MS~Error}{MS~Total}\)</span><br>
where:<br>
<span class="math inline">\(MS~Error\)</span> = <span class="math inline">\(frac{SSE}{n-k-1}\)</span><br>
<span class="math inline">\(MS~Total\)</span> = <span class="math inline">\(frac{SST}{n-1}\)</span><br>
therefore <span class="math inline">\(R^2_{adj}\)</span> can also be written as: <span class="math inline">\(R^2_{adj}=1-\frac{(1-R^2)*(n-1)}{(n-k-1)}\)</span></p></li>
</ul>
</section>
<section id="additional-variation-explained" class="level2">
<h2 class="anchored" data-anchor-id="additional-variation-explained">Additional variation explained</h2>
<ul>
<li><p>Variation in <span class="math inline">\(Y\)</span> is separated into two parts SSR and SSE.</p>
<ul>
<li>The shaded overlap of two circles represent the variation in <span class="math inline">\(Y\)</span> explained by the <span class="math inline">\(X\)</span> variables.</li>
</ul></li>
<li><p>The total overlap of <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>, and <span class="math inline">\(Y\)</span> depends on</p>
<ul>
<li>relationship of <span class="math inline">\(Y\)</span> with <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span></li>
<li>correlation between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span></li>
</ul>
<p><img src="img/5_5.png" class="img-fluid"></p></li>
</ul>
</section>
<section id="sequential-addition-of-predictors" class="level2">
<h2 class="anchored" data-anchor-id="sequential-addition-of-predictors">Sequential addition of predictors</h2>
<ul>
<li>Addition of variables decreases SSE and increases SSR and <span class="math inline">\(R^2\)</span>.</li>
<li><span class="math inline">\(s^2\)</span> = MSE = SSE/df decreases to a minimum and then increases since addition of variable decreases SSE but adds to df.</li>
</ul>
<p><img src="img/5_7.png" class="img-fluid"></p>
</section>
<section id="significance-of-type-i-or-seq.ss" class="level2">
<h2 class="anchored" data-anchor-id="significance-of-type-i-or-seq.ss">Significance of Type I or Seq.SS</h2>
<ul>
<li><p>The Type I SS is the SS of a predictor after adjusting for the effects of the <em>preceding</em> predictors in the model.</p>
<ul>
<li>Sometimes order matters, particularly with unequal sample sizes</li>
</ul></li>
<li><p>F test for the significance of the additional variation explained</p></li>
<li><p>R function <code>anova()</code> calculates sequential or Type-I SS</p></li>
</ul>
<p><img src="img/type1.png" class="img-fluid"></p>
</section>
<section id="type-ii" class="level2">
<h2 class="anchored" data-anchor-id="type-ii">Type II</h2>
<ul>
<li><p>Type II SS is based on the principle of marginality.</p>
<ul>
<li>Each variable effect is adjusted for all other appropriate effects.
<ul>
<li>equivalent to the Type I SS when the variable is the last predictor entered the model.</li>
</ul></li>
<li>Order matters for Type I SS but not for Type II SS</li>
</ul></li>
</ul>
<p><img src="img/type2.png" class="img-fluid"></p>
</section>
<section id="type-iii-ss" class="level2">
<h2 class="anchored" data-anchor-id="type-iii-ss">Type III SS</h2>
<ul>
<li><p>Type III SS is the SS added to the regression SS after <em>ALL</em> other predictors including an intercept term.</p>
<ul>
<li>Violates the marginality principle and so avoided for hypothesis tests</li>
</ul></li>
<li><p>SS explained is not always a good criterion for selection of variables</p></li>
</ul>
</section>
<section id="ss-types-in-action" class="level2">
<h2 class="anchored" data-anchor-id="ss-types-in-action">SS types in action</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(full_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Spread
            Df Sum Sq Mean Sq F value  Pr(&gt;F)    
PTS          1 141195  141195 1829.34 &lt; 2e-16 ***
P2p          1   4002    4002   51.85 8.3e-13 ***
P3p          1  14465   14465  187.42 &lt; 2e-16 ***
FTp          1    584     584    7.56   0.006 ** 
OREB         1   7082    7082   91.76 &lt; 2e-16 ***
DREB         1  78359   78359 1015.23 &lt; 2e-16 ***
AST          1     10      10    0.13   0.718    
STL          1  20082   20082  260.18 &lt; 2e-16 ***
BLK          1   1542    1542   19.98 8.2e-06 ***
Residuals 2108 162703      77                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(full_reg,  <span class="at">type=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: Spread
          Sum Sq   Df F value  Pr(&gt;F)    
PTS          416    1    5.38    0.02 *  
P2p        28767    1  372.71 &lt; 2e-16 ***
P3p        37787    1  489.57 &lt; 2e-16 ***
FTp         4497    1   58.26 3.4e-14 ***
OREB       10276    1  133.13 &lt; 2e-16 ***
DREB       83083    1 1076.43 &lt; 2e-16 ***
AST           41    1    0.53    0.47    
STL        19232    1  249.17 &lt; 2e-16 ***
BLK         1542    1   19.98 8.2e-06 ***
Residuals 162703 2108                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(full_reg,  <span class="at">type=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: Spread
            Sum Sq   Df F value  Pr(&gt;F)    
(Intercept) 189696    1 2457.72 &lt; 2e-16 ***
PTS            416    1    5.38    0.02 *  
P2p          28767    1  372.71 &lt; 2e-16 ***
P3p          37787    1  489.57 &lt; 2e-16 ***
FTp           4497    1   58.26 3.4e-14 ***
OREB         10276    1  133.13 &lt; 2e-16 ***
DREB         83083    1 1076.43 &lt; 2e-16 ***
AST             41    1    0.53    0.47    
STL          19232    1  249.17 &lt; 2e-16 ***
BLK           1542    1   19.98 8.2e-06 ***
Residuals   162703 2108                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="summary-so-far" class="level2">
<h2 class="anchored" data-anchor-id="summary-so-far">Summary so far</h2>
<ul>
<li>Defined multiple regression</li>
<li>Why we might run a multiple regression</li>
<li>How to perform a multiple regression, examine residuals, multicollinearity</li>
<li>Variation and R squared</li>
<li>Sums of Squares types</li>
</ul>
</section>
<section id="learning-objectives-1" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives-1">Learning Objectives:</h2>
<ul>
<li>Cautionary tales: when correlation misleads us</li>
<li>How to make models</li>
<li>Comparing models</li>
<li>Principles of model selection</li>
</ul>
</section>
<section id="does-waffle-houses-cause-divorce" class="level2">
<h2 class="anchored" data-anchor-id="does-waffle-houses-cause-divorce">Does Waffle Houses cause divorce??</h2>
<p><img src="img/waffleH2divorce.png" class="img-fluid"></p>
</section>
<section id="or-is-it-butter" class="level2">
<h2 class="anchored" data-anchor-id="or-is-it-butter">Or is it butter?</h2>
<p><img src="img/Divorce_margarine.png" class="img-fluid"></p>
<p>And if you want more to impress your friends at a BBQ, the source is: http://www.tylervigen.com/spurious-correlations</p>
</section>
<section id="spurious-association" class="level2">
<h2 class="anchored" data-anchor-id="spurious-association">Spurious association</h2>
<ul>
<li>You’ve heard that before: correlation does not imply causation. BUT it doesn’t discard it either</li>
<li>Hope you are seated: causation does not imply correlation.</li>
<li>Causation implies conditional correlation (up to linearity issues).</li>
<li>We need more than just statistical models to answer causal questions.</li>
</ul>
</section>
<section id="how-do-we-deal-with-spurious-associations" class="level2">
<h2 class="anchored" data-anchor-id="how-do-we-deal-with-spurious-associations">How do we deal with spurious associations?</h2>
<ul>
<li><p>Domain knowledge: you know that waffles and butter don’t <em>cause</em> divorce so why might they be correlated?</p>
<ul>
<li>Is there another predictor that would be better?</li>
</ul></li>
<li><p>Multiple regressions can disentangle the association between two predictors and an outcome</p>
<ul>
<li>Statistical control of a confound</li>
</ul></li>
</ul>
<p><img src="img/waffleH2divorce.png" class="img-fluid"></p>
</section>
<section id="masked-associations" class="level2">
<h2 class="anchored" data-anchor-id="masked-associations">Masked associations</h2>
<ul>
<li>Association between a predictor variable and an outcome can be masked.</li>
<li>You need to observe both to see the “true” influence of either on the outcome.</li>
<li>How do we account for the masking variable (seen as a nuisance)?</li>
</ul>
</section>
<section id="masking-situations-tend-to-arise-when" class="level2">
<h2 class="anchored" data-anchor-id="masking-situations-tend-to-arise-when">Masking situations tend to arise when:</h2>
<ul>
<li>Both predictors are associated with one another.</li>
<li>Have opposite relationships with the outcome</li>
</ul>
<p><img src="img/venetian-mask.jpg" class="img-fluid"></p>
</section>
<section id="milk-and-brain-data-example" class="level2">
<h2 class="anchored" data-anchor-id="milk-and-brain-data-example">Milk and brain data example</h2>
<p><img src="img/milk_brain_pic.png" class="img-fluid"></p>
</section>
<section id="primate-milk-data" class="level2">
<h2 class="anchored" data-anchor-id="primate-milk-data">Primate milk data</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/primate milk data-1.png" class="img-fluid figure-img" style="width:95.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="first-we-will-consider-simple-regressions" class="level2">
<h2 class="anchored" data-anchor-id="first-we-will-consider-simple-regressions">First we will consider simple regressions</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="multiple-regression-1" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-1">Multiple regression</h2>
<p><img src="img/milk_bivar_vs_multivar.png" class="img-fluid"></p>
</section>
<section id="masking-situation" class="level2">
<h2 class="anchored" data-anchor-id="masking-situation">Masking situation</h2>
<p>Tend to arise when</p>
<ul>
<li>Both predictors are associated with one another.</li>
<li>Have opposite relationships with the outcome</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/milk pairs-1.png" style="width:95.0%;height:50.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="how-do-we-deal-with-this" class="level2">
<h2 class="anchored" data-anchor-id="how-do-we-deal-with-this">How do we deal with this?</h2>
<ul>
<li>Statistically there is not really an answer</li>
<li>The answer lies in the causes and the causes are not in the data</li>
<li>Remember that interpreting the (regression) parameter estimates always depends upon what you believe the causal model</li>
</ul>
</section>
<section id="model-selection" class="level2">
<h2 class="anchored" data-anchor-id="model-selection">Model Selection</h2>
<ul>
<li>The first step before selection of the best subset of predictors is to study the correlation matrix</li>
<li>We then perform stepwise additions (forward) or subtractions (backward) from the model and compare them</li>
</ul>
<p>BUT…</p>
<ul>
<li>We saw with the illustration of SS how the significance or otherwise of a variable in a multiple regression model depends on the other variables in the model</li>
<li>Therefore, we cannot fully rely on the t-test and discard a variable because its coefficient is insignificant</li>
</ul>
</section>
<section id="selection-of-predictors" class="level2">
<h2 class="anchored" data-anchor-id="selection-of-predictors">Selection of predictors</h2>
<ul>
<li>Heuristic (short-cut) procedures based on criteria such as <span class="math inline">\(F\)</span>, <span class="math inline">\(R^2_{adj}\)</span>, <span class="math inline">\(AIC\)</span>, <span class="math inline">\(C_p\)</span> etc
<ul>
<li><p><code>Forward Selection</code>: Add variables sequentially</p>
<ul>
<li>convenient to obtain the simplest feasible model</li>
</ul></li>
<li><p><code>Backward Elimination</code>: Drop variables sequentially</p>
<ul>
<li><p>If difference between two variables is significant but not the variables themselves, forward regression would obtain the wrong model since both may not enter the model.</p>
<ul>
<li>Known as <em>suppressor</em> variables case (like masking variables discussed earlier)</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<p>Example: (try)</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1, data = suppressor)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.1691 -0.6791 -0.0033  0.6441  1.1299 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 11.98876    1.26689    9.46  3.4e-07 ***
x1           0.00375    0.41608    0.01     0.99    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.832 on 13 degrees of freedom
Multiple R-squared:  6.24e-06,  Adjusted R-squared:  -0.0769 
F-statistic: 8.11e-05 on 1 and 13 DF,  p-value: 0.993</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x2, data = suppressor)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.0900 -0.6334  0.0002  0.6146  1.0403 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   10.632      0.811   13.11  7.2e-09 ***
x2             0.195      0.113    1.74     0.11    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.75 on 13 degrees of freedom
Multiple R-squared:  0.188, Adjusted R-squared:  0.126 
F-statistic: 3.02 on 1 and 13 DF,  p-value: 0.106</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2, data = suppressor)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.01363 -0.00945 -0.00228  0.00863  0.01632 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -4.51541    0.06114   -73.8   &lt;2e-16 ***
x1           3.09701    0.01227   252.3   &lt;2e-16 ***
x2           1.03186    0.00368   280.1   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0107 on 12 degrees of freedom
Multiple R-squared:     1,  Adjusted R-squared:     1 
F-statistic: 3.92e+04 on 2 and 12 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
</section>
<section id="ockhams-razor" class="level2">
<h2 class="anchored" data-anchor-id="ockhams-razor">Ockham’s razor</h2>
<p><em>Nunca ponenda est pluralitas sine necesitate</em><br>
(Plurality should never be posited without necessity)</p>
<ul>
<li>Problem: fit to sample always (*multi-level models can be counter-examples) improves as we add parameters.</li>
<li>Dangers of “stargazing”: selecting variables with low p-values (aka ‘lots of stars’). P-values are not designed to cope with over-/under-fitting.</li>
</ul>
</section>
<section id="overfitting" class="level2">
<h2 class="anchored" data-anchor-id="overfitting">Overfitting</h2>
<ul>
<li>Overfitting learning too much from the data, where you are almost just connecting the points rather than estimating.</li>
<li>Underfitting is the opposite, i.e.&nbsp;being insensitive to the data.</li>
<li>aka Models with fewer assumptions are to be preferred.</li>
<li>In practice, we have to choose between models that differ both in accuracy and simplicity. The razor is not really a useful guidance for this trade off.</li>
</ul>
<p>We need tools</p>
</section>
<section id="all-possible-models" class="level2">
<h2 class="anchored" data-anchor-id="all-possible-models">All possible models:</h2>
<p>An exhaustive screening of all possible regression models can also be done using software</p>
<ul>
<li><code>Best Subsets</code>: Stop at each step and check whether predictors, in the model or outside, are the best combination for that step.<br>

<ul>
<li>time consuming to perform when the predictor set is large</li>
</ul></li>
</ul>
<p>Remember permutations</p>
<p>For example:</p>
<p>If we fix the number of predictors as 3, then 20 regression models are possible<br>
</p>
</section>
<section id="what-criteria-do-we-use" class="level2">
<h2 class="anchored" data-anchor-id="what-criteria-do-we-use">What criteria do we use?</h2>
<p>Multiple options<br>
- R squared<br>
- Sums of squared (different types, for testing predictor significance)<br>
- Information criteria (AIC, BIC etc)<br>
- For prediction: MSD/MSE, MAD, MAPE<br>
- <span class="math inline">\(C_p\)</span><br>
</p>
<p>Remember its about balance and what you are looking for (fit vs prediction, complexity vs generality)<br>
</p>
<ul>
<li><p><strong><code>Note</code></strong></p>
<ul>
<li>If a model stands out, it will perform well in terms of all summary measures.</li>
<li>If a model does not stand out, summary measures will contradict.</li>
</ul></li>
</ul>
</section>
<section id="when-r2-becomes-absurd" class="level2">
<h2 class="anchored" data-anchor-id="when-r2-becomes-absurd">When <span class="math inline">\(R^2\)</span> becomes absurd</h2>
<p><img src="img/brain_homin_R2ter.png" class="img-fluid"></p>
</section>
<section id="model-selection-1" class="level2">
<h2 class="anchored" data-anchor-id="model-selection-1">Model selection</h2>
<ul>
<li><p>Residual SD depends on its degrees of freedom</p>
<ul>
<li>So comparison of models based on Residual SD is not fully fair</li>
</ul></li>
<li><p>The following three measures are popular prediction modelling and similar to residual SD</p></li>
<li><p>Mean Squared Deviation (MSD): mean of the squared errors (i.e., deviations) (also called MSE)</p></li>
</ul>
<p><span class="math display">\[\frac{\sum \left({\rm observation-fit}\right)^{{\rm 2}} }{{\rm number~of~ observations}}\]</span></p>
<ul>
<li>Mean Absolute Deviation (MAD)</li>
</ul>
<p><span class="math display">\[\frac{\sum \left|{\rm observation-fit}\right| }{{\rm number~of~observations}}\]</span></p>
<ul>
<li>Mean Absolute Percentage Error (MAPE)</li>
</ul>
<p><span class="math display">\[\frac{\sum \frac{\left|{\rm observation-fit}\right|}{{\rm observation}} }{{\rm number~of~observations}} {\times100}\]</span></p>
</section>
<section id="model-selection-continued" class="level2">
<h2 class="anchored" data-anchor-id="model-selection-continued">Model selection (continued)</h2>
<ul>
<li><p>Avoid over-fitting.</p></li>
<li><p>So place a penalty for excessive model parameters</p></li>
<li><p>Akaike Information Criterion (AIC; <em>smaller is better</em>)</p></li>
</ul>
<p><span class="math display">\[AIC  =  n\log \left(\frac{SSE}{n} \right) + 2p\]</span> - Bayesian Information Criterion (BIC) places a higher penalty that depends on, the number of observations.</p>
<ul>
<li><p>As a result BIC fares well for selecting a model that explains the relationships well while AIC fares well when selecting a model for prediction purposes.</p></li>
<li><p>Other variations: WAIC, AICc, etc (we will not cover them)</p></li>
</ul>
</section>
<section id="model-selection-continued-1" class="level2">
<h2 class="anchored" data-anchor-id="model-selection-continued-1">Model selection (continued)</h2>
<ul>
<li><p>We can also benchmark a small model with the full regression</p></li>
<li><p>Mallow’s <span class="math inline">\(C_p\)</span> (look for <span class="math inline">\(C_p\)</span> just less than <span class="math inline">\(p\)</span> or equal)</p></li>
</ul>
<p><span class="math display">\[C_{p} =\; \frac{{\rm SS\; Error\; for\; Smaller\; Model}}{{\rm Mean\; Square\; Error\; for\; full\; regression}} -(n-2p)\]</span> - If unimportant variables are added to the model, then the variance of the fitted values will increase. Similarly if important variables are added, then the bias of the fitted values will decrease</p>
<ul>
<li>The <span class="math inline">\(C_{p}\)</span> index, balances the variance and bias</li>
</ul>
</section>
<section id="software" class="level2">
<h2 class="anchored" data-anchor-id="software">Software</h2>
<ul>
<li><p>In <span class="math inline">\(R\)</span>, <code>lm()</code> and <code>step()</code> function will perform the tasks</p>
<ul>
<li><code>leaps()</code> and <code>HH</code> packages contain additional functions</li>
<li><code>dredge()</code> in <code>MuMIn</code> will produce all the subset models given a full model</li>
<li>Also <code>MASS</code>, <code>car</code>, <code>caret</code>, and <code>SignifReg</code> R packages</li>
</ul></li>
<li><p>R base package step-wise selection is based on <span class="math inline">\(AIC\)</span> only.</p></li>
</ul>
</section>
<section id="cross-validation" class="level2">
<h2 class="anchored" data-anchor-id="cross-validation">Cross validation</h2>
<p>In sample error vs prediction error</p>
<ul>
<li>For simpler models, increasing the number of parameters improves the fit to the sample.</li>
<li>But it seems to reduce the accuracy of the out-of-sample predictions.</li>
<li>Most accurate models trade off flexibility (complexity) and overfitting</li>
</ul>
<p>General idea: - Leave out some observations. - Train the model on the remaining samples; score on those left out. - Average over many left-out sets to get the out-of-sample (future) accuracy.</p>
</section>
<section id="cross-validated-selection-data-example" class="level2">
<h2 class="anchored" data-anchor-id="cross-validated-selection-data-example">Cross validated selection: Data example</h2>
<p>Consider the pinetree data set which contains the circumference measurements of pine trees at four positions (First is bottom)</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="cross-validated-selection" class="level2">
<h2 class="anchored" data-anchor-id="cross-validated-selection">Cross validated selection</h2>
<ul>
<li>Model selection can be done focusing on prediction
<ul>
<li>method = “leapForward” &amp; method = “leapBackward” options</li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret);  <span class="fu">library</span>(leaps)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>fitControl  <span class="ot">&lt;-</span>  <span class="fu">trainControl</span>(<span class="at">method  =</span>  <span class="st">"repeatedcv"</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">number  =</span>  <span class="dv">5</span>,  <span class="at">repeats  =</span>  <span class="dv">100</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>leapBackwardfit  <span class="ot">&lt;-</span>  <span class="fu">train</span>(Top  <span class="sc">~</span>  .,  <span class="at">data  =</span>  pinetree[, <span class="sc">-</span><span class="dv">1</span>],</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="at">trControl  =</span>  fitControl,  <span class="at">method  =</span>  <span class="st">"leapBackward"</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(leapBackwardfit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
3 Variables  (and intercept)
       Forced in Forced out
Third      FALSE      FALSE
Second     FALSE      FALSE
First      FALSE      FALSE
1 subsets of each size up to 2
Selection Algorithm: backward
         Third Second First
1  ( 1 ) " "   " "    "*"  
2  ( 1 ) "*"   " "    "*"  </code></pre>
</div>
</div>
</section>
<section id="polynomial-models" class="level2">
<h2 class="anchored" data-anchor-id="polynomial-models">Polynomial models</h2>
<ul>
<li>A polynomial model includes the square, cube of predictor variables as additional variables.</li>
<li>High correlation (multicollinearity) between the predictor variables may be a problem in polynomial models, but not always.</li>
</ul>
</section>
<section id="polynomial-models-data-example" class="level2">
<h2 class="anchored" data-anchor-id="polynomial-models-data-example">Polynomial models: Data example</h2>
<p>We can fit a simple linear regression using the Pine tree data</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>pine1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Top <span class="sc">~</span> First, <span class="at">data =</span> pinetree) </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pine1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Top ~ First, data = pinetree)

Residuals:
   Min     1Q Median     3Q    Max 
-2.854 -0.881 -0.195  0.630  3.176 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -6.334      0.765   -8.28  2.1e-11 ***
First          0.763      0.024   31.78  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.29 on 58 degrees of freedom
Multiple R-squared:  0.946, Adjusted R-squared:  0.945 
F-statistic: 1.01e+03 on 1 and 58 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="look-closer" class="level2">
<h2 class="anchored" data-anchor-id="look-closer">Look closer</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looks non-linear</p>
</section>
<section id="polynomial-models-data-example-1" class="level2">
<h2 class="anchored" data-anchor-id="polynomial-models-data-example-1">Polynomial models: Data example</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                                  Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                         44.121      7.039    6.27        0
poly(First, degree = 3, raw = T)1   -3.972      0.695   -5.71        0
poly(First, degree = 3, raw = T)2    0.142      0.022    6.39        0
poly(First, degree = 3, raw = T)3   -0.001      0.000   -5.95        0</code></pre>
</div>
</div>
<pre><code>```         
- For the pinetree example, all the slope coefficients are highly significant for the cubic regression
- Not so for the quadratic regression
```</code></pre>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                                  Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                           3.85      2.450   1.569    0.122
poly(First, degree = 2, raw = T)1     0.10      0.155   0.646    0.521
poly(First, degree = 2, raw = T)2     0.01      0.002   4.319    0.000</code></pre>
</div>
</div>
<ul>
<li>Raw polynomials do not preserve the coefficient estimates but orthogonal polynomials do.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                         Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                 17.40      0.146  119.26        0
poly(First, degree = 2)1    41.01      1.130   36.29        0
poly(First, degree = 2)2     4.88      1.130    4.32        0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                         Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                 17.40      0.115  151.03        0
poly(First, degree = 3)1    41.01      0.892   45.96        0
poly(First, degree = 3)2     4.88      0.892    5.47        0
poly(First, degree = 3)3    -5.31      0.892   -5.95        0</code></pre>
</div>
</div>
</section>
<section id="residual-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="residual-diagnostics">Residual diagnostics</h2>
<ul>
<li><p>For multiple regression fits, including polynomial fits, examine the residuals as usual to-</p>
<pre><code>- Validate the model assumptions
- Look for model improvement clues</code></pre></li>
<li><p>Quadratic regression for pinetree data is not satisfactory based on the residual plots shown below:</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="categorical-predictors" class="level2">
<h2 class="anchored" data-anchor-id="categorical-predictors">Categorical predictors</h2>
<ul>
<li><p>Models can include categorical predictors such as <strong>Area</strong> in the pinetree dataset</p></li>
<li><p>Make sure that you use the <em>factor()</em> function when numerical codes are assigned to categorical variables.</p></li>
<li><p>Area effect on Top circumference is clear from the following plot</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter07_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="indicator-variables" class="level2">
<h2 class="anchored" data-anchor-id="indicator-variables">Indicator variables</h2>
<ul>
<li><p>Factors are employed in a multiple regression using indicator variables which are simply binary variables taking either zero or one</p></li>
<li><p>For for males and females, indicator variables are defined as follows:</p>
<ul>
<li>Indicator variable of males: <span class="math inline">\(~~~~~~~~\begin{array}{cccc} I_{\text {male}} &amp; = &amp; 1 &amp; \text{for males}\\ &amp; &amp; 0&amp; \text{for females} \end{array}\)</span></li>
<li>Indicator variable of females <span class="math inline">\(~~~~~~~~\begin{array}{cccc} I_{\text{female}} &amp; = &amp; 1 &amp; \text{for females}\\ &amp; &amp; 0&amp; \text{for males} \end{array}\)</span></li>
</ul></li>
<li><p>There are three different areas of the forest in the pinetree dataset. So we can define three indicator variables.</p></li>
<li><p>Only two indicator variables are needed because there is only 2 degrees of freedom for the 3 areas.</p></li>
</ul>
</section>
<section id="regression-output" class="level2">
<h2 class="anchored" data-anchor-id="regression-output">Regression output</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>Regression of Top Circumference on Area Indicator Variables</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">20.02</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">17.98</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">I2</td>
<td style="text-align: right;">-1.96</td>
<td style="text-align: right;">1.57</td>
<td style="text-align: right;">-1.24</td>
<td style="text-align: right;">0.22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I3</td>
<td style="text-align: right;">-5.92</td>
<td style="text-align: right;">1.57</td>
<td style="text-align: right;">-3.76</td>
<td style="text-align: right;">0.00</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li>The y-intercept is the mean of the response for the omitted category
<ul>
<li><code>20.02</code> is the mean Top circumference for the first Area</li>
</ul></li>
<li>slopes are the difference in the mean response
<ul>
<li><code>-1.96</code> is the drop in the mean top circumference in Area 2 when compared to Area 1 (which is not a significant drop)</li>
<li><code>-5.92</code> is the drop in the mean top circumference in Area 3 when compared to Area 1 (which is a highly significant drop)</li>
</ul></li>
</ul>
<p>Analysis of Covariance model employs both numerical and categorical predictors (covered later on).</p>
<ul>
<li>We specifically include the interaction between them</li>
</ul>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li><p>Regression methods aim to fit a model by least squares to explain the variation in the dependent variable <span class="math inline">\(Y\)</span> by fitting explanatory <span class="math inline">\(X\)</span> variables.</p></li>
<li><p>Matrix plots (EDA) and correlation coefficients provide important clues to the interrelationships.</p></li>
<li><p>For building a model, the additional variation explained is important. Summary criterion such as <span class="math inline">\(AIC\)</span> is also useful.</p></li>
<li><p>A model is not judged as the <strong>best</strong> purely on statistical grounds.</p></li>
</ul>
<!-- download.file("http://www.massey.ac.nz/~kgovinda/220exer/Chap5moreexamples.R", destfile="Chap5moreexamples.R") -->
<!-- download.file("https://www.massey.ac.nz/~kgovinda/220exer/chapter-5-exercises.html", destfile="chapter-5-exercises.html") -->
<!-- install.packages("remotes") -->
<!-- remotes::install_github("ricompute/ricomisc") -->
<!-- ricomisc::rstudio_viewer("chapter-4-exercises.html", file_path = NULL) -->


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>