---
title: "About"
---

This site contains materials for 161250 Data Analysis, including the [lecture slides](slides.qmd), [study guide](studyguide/index.qmd), [workshop code](workshops/ws01.qmd), and some extra code. The material is organised into 8 chapters, and all provided on one website for ease of access. Make use of the search function (using the magnifying glass icon on the top-right of the page)—it will allow you to quickly locate any text you enter across the whole site.

There is a lot of material on this site. You'll notice that the Study Guide is big, especially the first two chapters. But don't panic! **You can treat the lectures and workshops as the core, examinable material, and treat the Study Guide as a supplement.** The Study Guide is so big because it goes a bit deeper into some of the topics.

Feel free to use resources other than this site, particularly when coding (there are lots of links in the first workshop). The internet is full of Q & A about coding R. If you have a persistent error message, copy and paste it into an internet search engine with "R" or "Quarto". Large language models (LLMs), such as Bard and ChatGPT, are also very powerful tools to help with coding, if you can accurately describe what you want in words. Be careful though – LLMs often give you code that doesn't work, but they can be useful nonetheless.