<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>161250 Data Analysis - Chapter 7 Workshop</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../workshops/ws08.html" rel="next">
<link href="../workshops/ws06.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="../site_libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="../site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">161250 Data Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../slides.html" rel="" target="">
 <span class="menu-text">Slides</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../studyguide/index.html" rel="" target="">
 <span class="menu-text">Study Guide</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../workshops/ws01.html" rel="" target="" aria-current="page">
 <span class="menu-text">Workshops</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-extra-code" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Extra Code</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-extra-code">    
        <li>
    <a class="dropdown-item" href="../exercises/Chap2more.R" rel="" target="">
 <span class="dropdown-text">Ex2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap3more.R" rel="" target="">
 <span class="dropdown-text">Ex3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap4more.R" rel="" target="">
 <span class="dropdown-text">Ex4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap5more.R" rel="" target="">
 <span class="dropdown-text">Ex5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap6more.R" rel="" target="">
 <span class="dropdown-text">Ex6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap7more.R" rel="" target="">
 <span class="dropdown-text">Ex7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../exercises/Chap8more.R" rel="" target="">
 <span class="dropdown-text">Ex8</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../workshops/ws07.html">Chapter 7 Workshop</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../workshops/ws01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Getting Started With R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../workshops/ws02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2 Workshop</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../workshops/ws03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3 Workshop</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../workshops/ws04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4 Workshop</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../workshops/ws05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5 Workshop</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../workshops/ws06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 6 Workshop</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../workshops/ws07.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Chapter 7 Workshop</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../workshops/ws08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 8 Workshop</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#horse-hearts" id="toc-horse-hearts" class="nav-link active" data-scroll-target="#horse-hearts">Horse hearts</a>
  <ul class="collapse">
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data">Load data</a></li>
  <li><a href="#pairs-plot" id="toc-pairs-plot" class="nav-link" data-scroll-target="#pairs-plot">Pairs plot</a></li>
  <li><a href="#lm-output" id="toc-lm-output" class="nav-link" data-scroll-target="#lm-output"><code>lm</code> output</a></li>
  <li><a href="#variance-inflation-factor" id="toc-variance-inflation-factor" class="nav-link" data-scroll-target="#variance-inflation-factor">Variance Inflation Factor</a></li>
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection">Model selection</a></li>
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics">Model diagnostics</a></li>
  <li><a href="#d-plots" id="toc-d-plots" class="nav-link" data-scroll-target="#d-plots">3D plots</a></li>
  </ul></li>
  <li><a href="#dataset-prestige" id="toc-dataset-prestige" class="nav-link" data-scroll-target="#dataset-prestige">Dataset <strong><code>Prestige</code></strong></a>
  <ul class="collapse">
  <li><a href="#exercise-7.1" id="toc-exercise-7.1" class="nav-link" data-scroll-target="#exercise-7.1">Exercise 7.1</a></li>
  <li><a href="#exercise-7.2" id="toc-exercise-7.2" class="nav-link" data-scroll-target="#exercise-7.2">Exercise 7.2</a></li>
  <li><a href="#exercise-7.3" id="toc-exercise-7.3" class="nav-link" data-scroll-target="#exercise-7.3">Exercise 7.3</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="ws07.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Chapter 7 Workshop</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="horse-hearts" class="level1">
<h1>Horse hearts</h1>
<p>We will use the <em>horses’ hearts</em> dataset. There are seven variables represented as columns. They comprise six ultrasound measurements and the weights of 46 horses’ hearts, specifically:</p>
<ol type="1">
<li><code>INNERSYS</code> : Inner-wall ultrasound measurement in systole phase.</li>
<li><code>INNERDIA</code> : Inner-wall ultrasound measurement in diastole phase.</li>
<li><code>OUTERSYS</code> : Outer-wall ultrasound measurement in systole phase.</li>
<li><code>OUTERDIA</code> : Outer-wall ultrasound measurement in diastole phase.</li>
<li><code>EXTSYS</code> : Exterior ultrasound measurement in systole phase.</li>
<li><code>EXTDIA</code> : Exterior ultrasound measurement in diastole phase.</li>
<li><code>WEIGHT</code> : Weight in kilograms.</li>
</ol>
<p>We will build a multiple regression model to predict the weights of hearts using the six ultrasound measurements.</p>
<section id="load-data" class="level2">
<h2 class="anchored" data-anchor-id="load-data">Load data</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>hh <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www.massey.ac.nz/~anhsmith/data/horsehearts.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="pairs-plot" class="level2">
<h2 class="anchored" data-anchor-id="pairs-plot">Pairs plot</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(hh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="ws07_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This plot reveals some very high correlation amongst predictors, particularly (not surprisingly) between the same measurements taken in the different phases (diastolic and systolic). Thus, multicollinearity is likely to be a problem when fitting a multiple regression model. The challenge will be choose the subset of variables that provides the best model fit.</p>
</section>
<section id="lm-output" class="level2">
<h2 class="anchored" data-anchor-id="lm-output"><code>lm</code> output</h2>
<p>Let’s start by fitting the full model with all of the available predictor variables.</p>
<p>The formula <code>WEIGHT ~ .</code> fits a model with <code>WEIGHT</code> as the response variable and all other variables in the data frame as predictor variables.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mf <span class="ot">&lt;-</span> <span class="fu">lm</span>(WEIGHT <span class="sc">~</span> . , <span class="at">data =</span> hh)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = WEIGHT ~ ., data = hh)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.05051 -0.35313  0.01948  0.18674  2.09335 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  -1.6311     0.4879  -3.343  0.00184 **
INNERSYS      0.2321     0.3083   0.753  0.45617   
INNERDIA      0.5195     0.3954   1.314  0.19654   
OUTERSYS      0.7114     0.3288   2.164  0.03668 * 
OUTERDIA     -0.5574     0.4510  -1.236  0.22386   
EXTSYS       -0.2996     0.1346  -2.227  0.03182 * 
EXTDIA        0.3387     0.1475   2.296  0.02716 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6006 on 39 degrees of freedom
Multiple R-squared:  0.7525,    Adjusted R-squared:  0.7145 
F-statistic: 19.77 on 6 and 39 DF,  p-value: 1.922e-10</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting <code>summary.lm</code> output
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is a lot of information in the above summary output to process. Let’s break it down.</p>
<ol type="1">
<li><p>The <code>Call</code> part shows us the command we used to produce the model.</p></li>
<li><p>The <code>Residuals</code> part gives us a five-number summary of the residuals.</p></li>
<li><p>The <code>Coefficients</code> table provides the estimates of the model parameters. Specifically, the <code>Estimate</code> column gives us the estimates of the <span class="math inline">\(\beta\)</span>-coefficients, which can be used to reconstruct the predictive formula. Here, that formula is:</p>
<p><span class="math display">\[\hat y = -1.6311 + 0.2321 × INNERSYS + 0.5195 × INNERDIA + ... + 0.3387 × EXTDIA\]</span></p>
<p>The <code>Std. Error</code> column gives the standard error for the estimates of the coefficients. That is, the expected average deviation of the estimator of the coefficient (<span class="math inline">\(b\)</span> or <span class="math inline">\(\hat \beta\)</span>) from the true population parameter (<span class="math inline">\(\beta\)</span>). If we were to take many samples (of size <span class="math inline">\(n\)</span>) from this population, a coefficient’s standard error represents how much the estimate is expected to vary (due to sampling variation).</p>
<p>The <code>t value</code> is the estimate divided by its standard error, which can be used to test whether the effect of that variable is statistically different from zero. The p-value for this test is provided in the next column, headed <code>Pr(&gt;|t|)</code>. If the p-value is low, the observed coefficient estimate is unlikely to have resulted by chance due to sampling variation if the null hypothesis (<span class="math inline">\(H_0 : \beta = 0\)</span>) is true. Asterisks indicate significant results, as coded by the <code>Signif. codes</code>: given below the table.</p></li>
<li><p>The final three lines give results for the entire model.</p>
<p>The final three lines give results for the entire model.</p>
<p>The <code>Residual standard error</code> is an estimate of the standard deviation of the residuals, i.e.&nbsp;the average absolute difference between the predicted values and the actual values. When estimating the weight of horse’s hearts using this model, we would expect to, on average, be wrong by 0.6 kg. The <code>degrees of freedom</code> here are the residual degrees of freedom—the number of independent pieces of information with which the residual standard error was estimated.</p>
<p>Next, we have the <code>Multiple R-squared</code>, which is the proportion of the total variation in y that is explained by the model. Here, 75% of the variation is explained. The <code>Adjusted R-squared</code> is adjusted for the number of variables included in the model (see lecture slides). It cannot be interpreted in same way as the unadjusted <span class="math inline">\(R^2\)</span> can, but it can be used to compare models.</p>
<p>Finally, an <code>F-statistic</code>, associated degrees of freedom (<code>DF</code>) , and <code>p-value</code> are provided. This tests whether the model explains a significant proportion of the total variation in y. This can be thought of as testing whether any of the <span class="math inline">\(\beta\)</span> coefficients in model are non-zero. Here, the p-value is very small so we reject the null hypothesis that all of the <span class="math inline">\(\beta\)</span> coefficients in model are zero.</p></li>
</ol>
</div>
</div>
</section>
<section id="variance-inflation-factor" class="level2">
<h2 class="anchored" data-anchor-id="variance-inflation-factor">Variance Inflation Factor</h2>
<p>We mentioned earlier that we were concerned with multicollinearity—correlation among the predictors. A consequence of multicollinearity is that it increases the uncertainty in the estimates of the coefficients—the standard errors of the coefficients are inflated. We can quantify this effect, for each coefficient, with the Variance Inflation Factor (VIF). This is given by the function <code>car::vif()</code><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> INNERSYS  INNERDIA  OUTERSYS  OUTERDIA    EXTSYS    EXTDIA 
 8.772969  8.602746  7.706493  6.662813 16.046340 21.996455 </code></pre>
</div>
</div>
<p>According to a rule of thumb, a VIF &gt; 5 is cause for some concern. A VIF &gt; 10 is definitely problematic. So, we have a problem here.</p>
<p>The above VIF values pertain to variances. I find it more intuitive to discuss the square root of the VIF because they relate to the standard errors.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(car<span class="sc">::</span><span class="fu">vif</span>(mf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>INNERSYS INNERDIA OUTERSYS OUTERDIA   EXTSYS   EXTDIA 
2.961920 2.933044 2.776057 2.581242 4.005788 4.690038 </code></pre>
</div>
</div>
<p>These <span class="math inline">\(\sqrt{}\)</span>VIF values can be interpreted in the following way: the standard error for the effect of <code>INNERSYS</code> is around three times larger because of the presence of the other (correlated) variables in the model. The VIF is greatest for <code>EXTDIA</code>, which is consistent with this variable seeming to have the highest correlations with the other predictors.</p>
</section>
<section id="model-selection" class="level2">
<h2 class="anchored" data-anchor-id="model-selection">Model selection</h2>
<p>Statisticians use the term “parsimonious” to describe a model that contains no more predictors than necessary to adequately model the data—a model that has the right balance of complexity.</p>
<p>Let’s run a stepwise model selection process to try to find a more parsimonious model than the full model created above. The criterion we will use to assess the quality of the models is Akaike Information Criterion (AIC). Lower AIC values (i.e.&nbsp;closer to <span class="math inline">\(-\infty\)</span>) are better.</p>
<p>We will undertake a stepwise process in individual steps, using the <code>drop1()</code> function.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
WEIGHT ~ INNERSYS + INNERDIA + OUTERSYS + OUTERDIA + EXTSYS + 
    EXTDIA
         Df Sum of Sq    RSS     AIC
&lt;none&gt;                14.068 -40.500
INNERSYS  1   0.20434 14.272 -41.836
INNERDIA  1   0.62273 14.690 -40.507
OUTERSYS  1   1.68862 15.756 -37.285
OUTERDIA  1   0.55102 14.618 -40.732
EXTSYS    1   1.78829 15.856 -36.995
EXTDIA    1   1.90084 15.968 -36.670</code></pre>
</div>
</div>
<p>We have taken the full model (all predictors included) and asked what the AIC values<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> would be obtained if we dropped each one of the predictors (or none). The lowest AIC score is for the model with <code>INNERSYS</code> removed… so let’s remove it and then use <code>drop1()</code> again.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">update</span>(mf, <span class="sc">~</span> . <span class="sc">-</span> INNERSYS)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
WEIGHT ~ INNERDIA + OUTERSYS + OUTERDIA + EXTSYS + EXTDIA
         Df Sum of Sq    RSS     AIC
&lt;none&gt;                14.272 -41.836
INNERDIA  1   2.59025 16.862 -36.164
OUTERSYS  1   2.11154 16.383 -37.489
OUTERDIA  1   0.46718 14.739 -42.355
EXTSYS    1   1.59023 15.862 -38.977
EXTDIA    1   1.70093 15.973 -38.657</code></pre>
</div>
</div>
<p>Now we remove <code>OUTERDIA</code> and repeat.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">update</span>(m2, <span class="sc">~</span> . <span class="sc">-</span> OUTERDIA)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
WEIGHT ~ INNERDIA + OUTERSYS + EXTSYS + EXTDIA
         Df Sum of Sq    RSS     AIC
&lt;none&gt;                14.739 -42.355
INNERDIA  1    3.2083 17.947 -35.295
OUTERSYS  1    2.0972 16.836 -38.235
EXTSYS    1    1.3505 16.090 -40.322
EXTDIA    1    1.3250 16.064 -40.395</code></pre>
</div>
</div>
<p>This time, the best model is that with none removed, so the model selection process stops there. Note that this whole process could have been done in a single line of code.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mstep <span class="ot">&lt;-</span> <span class="fu">step</span>(mf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-40.5
WEIGHT ~ INNERSYS + INNERDIA + OUTERSYS + OUTERDIA + EXTSYS + 
    EXTDIA

           Df Sum of Sq    RSS     AIC
- INNERSYS  1   0.20434 14.272 -41.836
- OUTERDIA  1   0.55102 14.618 -40.732
- INNERDIA  1   0.62273 14.690 -40.507
&lt;none&gt;                  14.068 -40.500
- OUTERSYS  1   1.68862 15.756 -37.285
- EXTSYS    1   1.78829 15.856 -36.995
- EXTDIA    1   1.90084 15.968 -36.670

Step:  AIC=-41.84
WEIGHT ~ INNERDIA + OUTERSYS + OUTERDIA + EXTSYS + EXTDIA

           Df Sum of Sq    RSS     AIC
- OUTERDIA  1   0.46718 14.739 -42.355
&lt;none&gt;                  14.272 -41.836
- EXTSYS    1   1.59023 15.862 -38.977
- EXTDIA    1   1.70093 15.973 -38.657
- OUTERSYS  1   2.11154 16.383 -37.489
- INNERDIA  1   2.59025 16.862 -36.164

Step:  AIC=-42.35
WEIGHT ~ INNERDIA + OUTERSYS + EXTSYS + EXTDIA

           Df Sum of Sq    RSS     AIC
&lt;none&gt;                  14.739 -42.355
- EXTDIA    1    1.3250 16.064 -40.395
- EXTSYS    1    1.3505 16.090 -40.322
- OUTERSYS  1    2.0972 16.836 -38.235
- INNERDIA  1    3.2083 17.947 -35.295</code></pre>
</div>
</div>
<p>When you run this, the whole three-step process we executed above will print onscreen and the object <code>mstep</code> represents the stepwise-selected model.</p>
<p>Let’s examine the stepwise model.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mstep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = WEIGHT ~ INNERDIA + OUTERSYS + EXTSYS + EXTDIA, 
    data = hh)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.19400 -0.31530 -0.05037  0.20522  1.92298 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  -1.5120     0.4681  -3.230  0.00244 **
INNERDIA      0.7991     0.2675   2.987  0.00473 **
OUTERSYS      0.4931     0.2042   2.415  0.02026 * 
EXTSYS       -0.2360     0.1218  -1.938  0.05950 . 
EXTDIA        0.2500     0.1302   1.920  0.06185 . 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5996 on 41 degrees of freedom
Multiple R-squared:  0.7407,    Adjusted R-squared:  0.7154 
F-statistic: 29.28 on 4 and 41 DF,  p-value: 1.554e-11</code></pre>
</div>
</div>
<p>We still have two variables that are very highly correlated: <code>EXTSYS</code> and <code>EXTDIA</code>. Let’s see if this correlation is problematic, according to the VIF criterion.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mstep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> INNERDIA  OUTERSYS    EXTSYS    EXTDIA 
 3.950323  2.981334 13.184774 17.198270 </code></pre>
</div>
</div>
<p>With VIF scores for these two variables still well above 5, this is certainly a problem. This illustrates an important point: you must not naively accept a model which results from a stepwise selection process. Always scrutinise a model before accepting it.</p>
<p>We will force a step where we drop either <code>EXTSYS</code> or <code>EXTDIA</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mstep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
WEIGHT ~ INNERDIA + OUTERSYS + EXTSYS + EXTDIA
         Df Sum of Sq    RSS     AIC
&lt;none&gt;                14.739 -42.355
INNERDIA  1    3.2083 17.947 -35.295
OUTERSYS  1    2.0972 16.836 -38.235
EXTSYS    1    1.3505 16.090 -40.322
EXTDIA    1    1.3250 16.064 -40.395</code></pre>
</div>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>mstep2 <span class="ot">&lt;-</span> <span class="fu">update</span>(mstep,  <span class="sc">~</span> . <span class="sc">-</span> EXTDIA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now, let’s try another step.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mstep2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
WEIGHT ~ INNERDIA + OUTERSYS + EXTSYS
         Df Sum of Sq    RSS     AIC
&lt;none&gt;                16.064 -40.395
INNERDIA  1    5.0919 21.156 -29.729
OUTERSYS  1    3.3053 19.369 -33.788
EXTSYS    1    0.1091 16.173 -42.083</code></pre>
</div>
</div>
<p>It seems that the model with <code>EXTSYS</code> removed, leaving only <code>INNERDIA</code> and <code>OUTERSYS</code>, is actually preferable. Once the latter two variables are included, <code>EXTSYS</code> does not add any strength to the model. Let’s make this model and check for further removals, and our VIFs.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>mstep3 <span class="ot">&lt;-</span> <span class="fu">update</span>(mstep2, <span class="sc">~</span> . <span class="sc">-</span> EXTSYS)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mstep3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
WEIGHT ~ INNERDIA + OUTERSYS
         Df Sum of Sq    RSS     AIC
&lt;none&gt;                16.173 -42.083
INNERDIA  1    6.2151 22.388 -29.125
OUTERSYS  1    3.2771 19.450 -35.596</code></pre>
</div>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mstep3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>INNERDIA OUTERSYS 
2.471453 2.471453 </code></pre>
</div>
</div>
<p>It seems that this model cannot be improved by dropping any further variables. The variables <code>INNERDIA</code> and <code>OUTERSYS</code>, though correlated (r = 0.77), do not exert undue influence on each other in the model.</p>
<p>To summarise, let’s see the AIC scores for all the models we’ve made so far.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mf, m2, m3, mstep, mstep2, mstep3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       df      AIC
mf      8 92.04262
m2      7 90.70599
m3      6 90.18764
mstep   6 90.18764
mstep2  5 92.14759
mstep3  4 90.45888</code></pre>
</div>
</div>
<p>All of these models have very similar AIC. Statisticians say that AIC scores within, say, 3 points can be considered equivalent, and so often we take the approach of choosing the simplest model (i.e.&nbsp;that with the fewest predictors) of all those within 3 AIC points of the lowest score. In some fields it is common to report all models within 10 AIC points or produce an ensemble model bases on AIC weight (not covered in this course). So, while the <code>mstep3</code> model isn’t the absolute lowest, it is the simplest model from a bunch of models with roughly equivalent AIC scores. Also, it is a good choice because it doesn’t have the problems with severe multicollinearity found in the other models.</p>
<p>Don’t worry about the fact that the two functions <code>drop1()</code> and <code>AIC()</code> give different scores. Remember the AIC is a tool for comparing models—the actual scores don’t matter. If you look at the difference in AIC scores between two models from the two functions, they are the same. It also should not be compared on models that have different data sources because it is unit less and only acts to compare the models in a specific set.</p>
<p>Difference between AIC scores for <code>mstep2</code> and <code>mstep3</code> from the <code>drop1(mstep2)</code> output:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40.395</span> <span class="sc">-</span> (<span class="sc">-</span><span class="fl">42.083</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.688</code></pre>
</div>
</div>
<p>And from the <code>AIC(mf, m2, m3, mstep, mstep2, mstep3)</code> output:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fl">92.14759</span> <span class="sc">-</span> <span class="fl">90.45888</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.68871</code></pre>
</div>
</div>
<p>So now we can choose <code>mstep3</code> and clean up.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(mf, m2, m3, mstep, mstep2) <span class="co"># this code removes these variables</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s examine the summary for our chosen model.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mstep3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = WEIGHT ~ INNERDIA + OUTERSYS, data = hh)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.08663 -0.33797 -0.08511  0.32755  1.82971 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -1.4948     0.3728  -4.009 0.000238 ***
INNERDIA      0.8797     0.2164   4.065 0.000201 ***
OUTERSYS      0.5612     0.1901   2.952 0.005100 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6133 on 43 degrees of freedom
Multiple R-squared:  0.7155,    Adjusted R-squared:  0.7023 
F-statistic: 54.07 on 2 and 43 DF,  p-value: 1.833e-12</code></pre>
</div>
</div>
<p>We are now explaining 72% of the variation in heart weights with two variables, as opposed to 75% of the variation with six variables in the original full model. Note also that, in the full model, <code>INNERDIA</code> was not significant and <code>OUTERSYS</code> was only weakly significant. In the smaller model, both these predictors were highly significant. Personally, I would definitely prefer the more parsimonious two-variable model, especially if it meant that I had only to take two, rather than six, ultrasound measurements on a thousand horses!</p>
<p>But we’re not done yet. We must use some diagnostic tools to examine whether our model meets the assumptions of linear regression before we can accept it.</p>
</section>
<section id="model-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="model-diagnostics">Model diagnostics</h2>
<p>Examine the usual four diagnostic plots.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mstep3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="ws07_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ws07_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ws07_files/figure-html/unnamed-chunk-24-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ws07_files/figure-html/unnamed-chunk-24-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Residuals-vs-Fitted plot shows a slight decreasing trend in the residuals at low fitted values, but it is only a few points. It might pay, though, to bear in mind that the model is likely to overestimate lower heart weights.</p>
<p>The normal Q-Q plot is not too worrying, although there are a few higher-than-expected residuals.</p>
<p>The Scale-Location plot shows no strong evidence of heteroscedasticity—the variance appears fairly constant across fitted values.</p>
<p>And, finally, there are no very large values of Cook’s distance or leverage.</p>
<p>There are many other diagnostic tools and graphs available, many in the <code>car</code> library, which we do not have time to go into here. If you’re interested, this website is a good place to start: <a href="http://www.statmethods.net/stats/rdiagnostics.html" class="uri">http://www.statmethods.net/stats/rdiagnostics.html</a>.</p>
</section>
<section id="d-plots" class="level2">
<h2 class="anchored" data-anchor-id="d-plots">3D plots</h2>
<p>Since there are three variables involved in this model, it might be useful to examine their relationship using 3D plots. We can include the 2D plane that represents our regression model on the plot, using the following code.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scatterplot3d)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>hh3d <span class="ot">&lt;-</span> <span class="fu">scatterplot3d</span>(</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  hh<span class="sc">$</span>INNERDIA, </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  hh<span class="sc">$</span>OUTERSYS, </span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  hh<span class="sc">$</span>WEIGHT,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">type=</span><span class="st">"h"</span>, </span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">highlight.3d=</span>T,</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">16</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>hh3d<span class="sc">$</span><span class="fu">plane3d</span>(mstep3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="ws07_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Finally, use <code>plotly</code> to create a dynamic 3D plot which you can rotate using your mouse. Don’t say I never treat you!</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_ly</span>(</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  hh, </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="sc">~</span>INNERDIA, </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="sc">~</span>OUTERDIA, </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">z =</span> <span class="sc">~</span>WEIGHT</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_markers</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-a6e2f080d653ecf859a6" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-a6e2f080d653ecf859a6">{"x":{"visdat":{"f5f81dc94e4e":["function () ","plotlyVisDat"]},"cur_data":"f5f81dc94e4e","attrs":{"f5f81dc94e4e":{"x":{},"y":{},"z":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d","mode":"markers","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"INNERDIA"},"yaxis":{"title":"OUTERDIA"},"zaxis":{"title":"WEIGHT"}},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[1.8999999999999999,1.7,1.8999999999999999,2,2.7999999999999998,2.2999999999999998,2.5,2.7000000000000002,2.2000000000000002,2.6000000000000001,2.2999999999999998,2.8999999999999999,2.2999999999999998,2.5,2.6000000000000001,1.3999999999999999,2,3.7999999999999998,2.2999999999999998,2.3999999999999999,2.1000000000000001,1.8999999999999999,2.2999999999999998,1.8,1.7,2.3999999999999999,1.3,1.8999999999999999,2,1.3999999999999999,2.2000000000000002,2.2000000000000002,2.2999999999999998,1.3,3.7000000000000002,2.2000000000000002,3.7999999999999998,3.2000000000000002,3.2000000000000002,3.1000000000000001,4,3.2999999999999998,2.5,2.2000000000000002,2.1000000000000001,3.2999999999999998],"y":[1.5,1.7,1.7,1.7,2,1.7,2,2.5,1.8,2,2.2000000000000002,2.6000000000000001,2.1000000000000001,1.5,2.6000000000000001,1.3,1.8,2.2000000000000002,2,1.6000000000000001,1.7,1.7,2.2000000000000002,1.3,1.2,1.6000000000000001,1.2,1.5,1.6000000000000001,1.3999999999999999,1.3999999999999999,1.3999999999999999,2.1000000000000001,1,2.3999999999999999,1.5,3,2.2999999999999998,2.1000000000000001,2.6000000000000001,2.1000000000000001,2.2000000000000002,2.2000000000000002,2.2999999999999998,3,3.2999999999999998],"z":[1.4319999999999999,1.226,1.46,1.3540000000000001,2.2109999999999999,1.212,1.8,1.758,1.7010000000000001,1.51,1.9139999999999999,2.9980000000000002,2.2610000000000001,2.2400000000000002,1.8,1.276,1.5169999999999999,3.2959999999999998,1.8779999999999999,1.7509999999999999,1.3959999999999999,1.772,2.9980000000000002,1.2050000000000001,1.637,1.3109999999999999,1.091,1.155,1.0349999999999999,0.999,1.5589999999999999,1.4810000000000001,1.6579999999999999,1.5,4.6829999999999998,1.6619999999999999,4.2409999999999997,4.5720000000000001,4.0999999999999996,3.7200000000000002,4.3150000000000004,4.3200000000000003,3.3900000000000001,4.0099999999999998,2.9700000000000002,3.431],"type":"scatter3d","mode":"markers","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>I do not recommend 3-D plots for print reports/publications. They are often best viewed interactively. Instead try using colors or bubbles for continuous third variables and shapes or facets for discrete third variables.</p>
<p>For example:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>hh <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span>OUTERDIA, <span class="at">x=</span>INNERDIA, <span class="at">color=</span>WEIGHT))<span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="ws07_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="dataset-prestige" class="level1">
<h1>Dataset <strong><code>Prestige</code></strong></h1>
<p>We will continue to use dataset <code>Prestige</code> from the <code>car</code> R package.</p>
<section id="exercise-7.1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-7.1">Exercise 7.1</h2>
<p>Obtain the matrix plot of the numerical variables <code>education</code>, <code>income</code>, <code>women</code>, and <code>prestige</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>Prestige <span class="sc">|&gt;</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(prestige, education, income, women) <span class="sc">|&gt;</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggpairs</span>(<span class="fu">aes</span>(<span class="at">colour=</span>Prestige<span class="sc">$</span>type))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Obtain their correlation matrix.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Old style pairs plot</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>Prestige <span class="sc">|&gt;</span> </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(prestige, education, income, women) <span class="sc">|&gt;</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>Prestige <span class="sc">|&gt;</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(prestige, education, income, women) <span class="sc">|&gt;</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Fit a (full) multiple regression of <code>prestige</code> on <code>education</code>, <code>income</code>, &amp; <code>women</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>full.reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> income <span class="sc">+</span> women,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> Prestige)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Obtain the plots for residual diagnostics. Residual plots</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(full.reg, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Old style plots</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(full.reg, <span class="dv">1</span>) <span class="co"># the argument 1 can be changed up to 6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or just use</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(full.reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Regression outputs</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full.reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prestige ~ education + income + women, data = Prestige)

Residuals:
     Min       1Q   Median       3Q      Max 
-19.8246  -5.3332  -0.1364   5.1587  17.5045 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -6.7943342  3.2390886  -2.098   0.0385 *  
education    4.1866373  0.3887013  10.771  &lt; 2e-16 ***
income       0.0013136  0.0002778   4.729 7.58e-06 ***
women       -0.0089052  0.0304071  -0.293   0.7702    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.846 on 98 degrees of freedom
Multiple R-squared:  0.7982,    Adjusted R-squared:  0.792 
F-statistic: 129.2 on 3 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(full.reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: prestige
          Df  Sum Sq Mean Sq  F value    Pr(&gt;F)    
education  1 21608.4 21608.4 350.9741 &lt; 2.2e-16 ***
income     1  2248.1  2248.1  36.5153 2.739e-08 ***
women      1     5.3     5.3   0.0858    0.7702    
Residuals 98  6033.6    61.6                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">extractAIC</span>(full.reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   4.0000 424.1724</code></pre>
</div>
</div>
</section>
<section id="exercise-7.2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-7.2">Exercise 7.2</h2>
<p>Perform stepwise regression analysis of <code>prestige</code> on <code>education</code>, <code>income</code>, &amp; <code>women</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>full.reg <span class="ot">=</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> income <span class="sc">+</span> women,</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> Prestige)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(full.reg)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(full.reg, <span class="at">direction=</span><span class="st">"backward"</span>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(full.reg, <span class="at">direction=</span><span class="st">"both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The function <code>update()</code> is handy for making adjustments to a model. For example, see try the following codes:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">=</span> <span class="fu">update</span>(full.reg,  . <span class="sc">~</span> . <span class="sc">-</span> women)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Note that <code>. ~ . - women</code> means that the model is fitted without the <code>women</code> variable.</p>
<p>Further options are available in <code>leaps</code> and <code>HH</code> packages (installation commands are given below).</p>
<p><code>install.packages("leaps", repos = "https://cran.r-project.org")</code> <code>install.packages("HH", repos = "https://cran.r-project.org")</code></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">regsubsets</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> income <span class="sc">+</span> women, </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> Prestige)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HH)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summaryHH</span>(model)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">summaryHH</span>(model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="exercise-7.3" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-7.3">Exercise 7.3</h2>
<p>Perform a polynomial regression of <code>prestige</code> on <code>income</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cubic fit</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>p.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> <span class="fu">poly</span>(income,<span class="dv">3</span>),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> Prestige)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p.model)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="fu">extractAIC</span>(p.model)</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(p.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ul>
<li>More R code examples are <a href="../exercises/Chap7more.R">here</a></li>
</ul>


<!-- -->

</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The <code>car::vif()</code> notation calls the function <code>vif()</code> from within the package <code>car</code>. Alternatively, you can load the package into R with the command <code>library(car)</code>. After doing this, all functions in the car package become available, so you can call the function directly as <code>vif()</code>, omitting the <code>car::</code>. Either way, you must have the package installed, of course!<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Negative values of AIC, as seen here, are uncommon but are nothing to worry about. This occurs when the values of the response variable are small.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../workshops/ws06.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Chapter 6 Workshop</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../workshops/ws08.html" class="pagination-link">
        <span class="nav-page-text">Chapter 8 Workshop</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb63" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Chapter 7 Workshop"</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo=FALSE, message=FALSE}</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>, <span class="at">comment=</span><span class="cn">NA</span>)</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a><span class="fu"># Horse hearts</span></span>
<span id="cb63-17"><a href="#cb63-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-18"><a href="#cb63-18" aria-hidden="true" tabindex="-1"></a>We will use the *horses’ hearts* dataset. There are seven variables represented as columns. They comprise six ultrasound measurements and the weights of 46 horses’ hearts, specifically:</span>
<span id="cb63-19"><a href="#cb63-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-20"><a href="#cb63-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-21"><a href="#cb63-21" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span><span class="in">`INNERSYS`</span> : Inner-wall ultrasound measurement in systole phase.</span>
<span id="cb63-22"><a href="#cb63-22" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span><span class="in">`INNERDIA`</span> : Inner-wall ultrasound measurement in diastole phase.</span>
<span id="cb63-23"><a href="#cb63-23" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span><span class="in">`OUTERSYS`</span> : Outer-wall ultrasound measurement in systole phase.</span>
<span id="cb63-24"><a href="#cb63-24" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span><span class="in">`OUTERDIA`</span> : Outer-wall ultrasound measurement in diastole phase.</span>
<span id="cb63-25"><a href="#cb63-25" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span><span class="in">`EXTSYS`</span>   : Exterior ultrasound measurement in systole phase.</span>
<span id="cb63-26"><a href="#cb63-26" aria-hidden="true" tabindex="-1"></a><span class="ss">6.  </span><span class="in">`EXTDIA`</span>   : Exterior ultrasound measurement in diastole phase.</span>
<span id="cb63-27"><a href="#cb63-27" aria-hidden="true" tabindex="-1"></a><span class="ss">7.  </span><span class="in">`WEIGHT`</span>   : Weight in kilograms.       </span>
<span id="cb63-28"><a href="#cb63-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-29"><a href="#cb63-29" aria-hidden="true" tabindex="-1"></a>We will build a multiple regression model to predict the weights of hearts using the six ultrasound measurements. </span>
<span id="cb63-30"><a href="#cb63-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-31"><a href="#cb63-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Load data</span></span>
<span id="cb63-32"><a href="#cb63-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-35"><a href="#cb63-35" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-36"><a href="#cb63-36" aria-hidden="true" tabindex="-1"></a>hh <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www.massey.ac.nz/~anhsmith/data/horsehearts.csv"</span>)</span>
<span id="cb63-37"><a href="#cb63-37" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-38"><a href="#cb63-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-39"><a href="#cb63-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-40"><a href="#cb63-40" aria-hidden="true" tabindex="-1"></a><span class="fu">## Pairs plot</span></span>
<span id="cb63-41"><a href="#cb63-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-44"><a href="#cb63-44" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-45"><a href="#cb63-45" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb63-46"><a href="#cb63-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-47"><a href="#cb63-47" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(hh)</span>
<span id="cb63-48"><a href="#cb63-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-49"><a href="#cb63-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-50"><a href="#cb63-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-51"><a href="#cb63-51" aria-hidden="true" tabindex="-1"></a>This plot reveals some very high correlation amongst predictors, particularly (not surprisingly) between the same measurements taken in the different phases (diastolic and systolic). Thus, multicollinearity is likely to be a problem when fitting a multiple regression model. The challenge will be choose the subset of variables that provides the best model fit. </span>
<span id="cb63-52"><a href="#cb63-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-53"><a href="#cb63-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-54"><a href="#cb63-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-55"><a href="#cb63-55" aria-hidden="true" tabindex="-1"></a><span class="fu">## `lm` output</span></span>
<span id="cb63-56"><a href="#cb63-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-57"><a href="#cb63-57" aria-hidden="true" tabindex="-1"></a>Let’s start by fitting the full model with all of the available predictor variables. </span>
<span id="cb63-58"><a href="#cb63-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-59"><a href="#cb63-59" aria-hidden="true" tabindex="-1"></a>The formula <span class="in">`WEIGHT ~ .`</span> fits a model with <span class="in">`WEIGHT`</span> as the response variable and all other variables in the data frame as predictor variables.</span>
<span id="cb63-60"><a href="#cb63-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-63"><a href="#cb63-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-64"><a href="#cb63-64" aria-hidden="true" tabindex="-1"></a>mf <span class="ot">&lt;-</span> <span class="fu">lm</span>(WEIGHT <span class="sc">~</span> . , <span class="at">data =</span> hh)</span>
<span id="cb63-65"><a href="#cb63-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-66"><a href="#cb63-66" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf)</span>
<span id="cb63-67"><a href="#cb63-67" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-68"><a href="#cb63-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-69"><a href="#cb63-69" aria-hidden="true" tabindex="-1"></a>:::{.callout-tip}</span>
<span id="cb63-70"><a href="#cb63-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-71"><a href="#cb63-71" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpreting `summary.lm` output</span></span>
<span id="cb63-72"><a href="#cb63-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-73"><a href="#cb63-73" aria-hidden="true" tabindex="-1"></a>There is a lot of information in the above summary output to process. Let’s break it down.</span>
<span id="cb63-74"><a href="#cb63-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-75"><a href="#cb63-75" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>The <span class="in">`Call`</span> part shows us the command we used to produce the model. </span>
<span id="cb63-76"><a href="#cb63-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-77"><a href="#cb63-77" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>The <span class="in">`Residuals`</span> part gives us a five-number summary of the residuals. </span>
<span id="cb63-78"><a href="#cb63-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-79"><a href="#cb63-79" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>The <span class="in">`Coefficients`</span> table provides the estimates of the model parameters. Specifically, the <span class="in">`Estimate`</span> column gives us the estimates of the $\beta$-coefficients, which can be used to reconstruct the predictive formula. Here, that formula is: </span>
<span id="cb63-80"><a href="#cb63-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-81"><a href="#cb63-81" aria-hidden="true" tabindex="-1"></a>    $$\hat y = -1.6311 + 0.2321 × INNERSYS + 0.5195 × INNERDIA + ... + 0.3387 × EXTDIA$$</span>
<span id="cb63-82"><a href="#cb63-82" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb63-83"><a href="#cb63-83" aria-hidden="true" tabindex="-1"></a>    The <span class="in">`Std. Error`</span> column gives the standard error for the estimates of the coefficients. That is, the expected average deviation of the estimator of the coefficient ($b$ or $\hat \beta$) from the true population parameter ($\beta$). If we were to take many samples (of size $n$) from this population, a coefficient’s standard error represents how much the estimate is expected to vary (due to sampling variation). </span>
<span id="cb63-84"><a href="#cb63-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-85"><a href="#cb63-85" aria-hidden="true" tabindex="-1"></a>    The <span class="in">`t value`</span> is the estimate divided by its standard error, which can be used to test whether the effect of that variable is statistically different from zero. The p-value for this test is provided in the next column, headed <span class="in">`Pr(&gt;|t|)`</span>. If the p-value is low, the observed coefficient estimate is unlikely to have resulted by chance due to sampling variation if the null hypothesis ($H_0 : \beta = 0$) is true. Asterisks indicate significant results, as coded by the <span class="in">`Signif. codes`</span>:  given below the table.</span>
<span id="cb63-86"><a href="#cb63-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-87"><a href="#cb63-87" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>The final three lines give results for the entire model.</span>
<span id="cb63-88"><a href="#cb63-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-89"><a href="#cb63-89" aria-hidden="true" tabindex="-1"></a>    The final three lines give results for the entire model.</span>
<span id="cb63-90"><a href="#cb63-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-91"><a href="#cb63-91" aria-hidden="true" tabindex="-1"></a>    The <span class="in">`Residual standard error`</span> is an estimate of the standard deviation of the residuals, i.e. the average absolute difference between the predicted values and the actual values. When estimating the weight of horse’s hearts using this model, we would expect to, on average, be wrong by 0.6 kg. The <span class="in">`degrees of freedom`</span> here are the residual degrees of freedom—the number of independent pieces of information with which the residual standard error was estimated.</span>
<span id="cb63-92"><a href="#cb63-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-93"><a href="#cb63-93" aria-hidden="true" tabindex="-1"></a>    Next, we have the <span class="in">`Multiple R-squared`</span>, which is the proportion of the total variation in y that is explained by the model. Here, 75% of the variation is explained. The <span class="in">`Adjusted R-squared`</span> is adjusted for the number of variables included in the model (see lecture slides). It cannot be interpreted in same way as the unadjusted $R^2$ can, but it can be used to compare models.</span>
<span id="cb63-94"><a href="#cb63-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-95"><a href="#cb63-95" aria-hidden="true" tabindex="-1"></a>    Finally, an <span class="in">`F-statistic`</span>, associated degrees of freedom (<span class="in">`DF`</span>) , and <span class="in">`p-value`</span> are provided. This tests whether the model explains a significant proportion of the total variation in y. This can be thought of as testing whether any of the $\beta$ coefficients in model are non-zero. Here, the p-value is very small so we reject the null hypothesis that all of the $\beta$ coefficients in model are zero.</span>
<span id="cb63-96"><a href="#cb63-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-97"><a href="#cb63-97" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb63-98"><a href="#cb63-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-99"><a href="#cb63-99" aria-hidden="true" tabindex="-1"></a><span class="fu">## Variance Inflation Factor</span></span>
<span id="cb63-100"><a href="#cb63-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-101"><a href="#cb63-101" aria-hidden="true" tabindex="-1"></a>We mentioned earlier that we were concerned with multicollinearity—correlation among the predictors. A consequence of multicollinearity is that it increases the uncertainty in the estimates of the coefficients—the standard errors of the coefficients are inflated. We can quantify this effect, for each coefficient, with the Variance Inflation Factor (VIF). This is given by the function <span class="in">`car::vif()`</span><span class="ot">[^1]</span>. </span>
<span id="cb63-102"><a href="#cb63-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-103"><a href="#cb63-103" aria-hidden="true" tabindex="-1"></a><span class="ot">[^1]: </span>The <span class="in">`car::vif()`</span> notation calls the function <span class="in">`vif()`</span> from within the package <span class="in">`car`</span>. Alternatively, you can load the package into R with the command <span class="in">`library(car)`</span>. After doing this, all functions in the car package become available, so you can call the function directly as <span class="in">`vif()`</span>, omitting the <span class="in">`car::`</span>. Either way, you must have the package installed, of course!</span>
<span id="cb63-104"><a href="#cb63-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-105"><a href="#cb63-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-108"><a href="#cb63-108" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-109"><a href="#cb63-109" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mf)</span>
<span id="cb63-110"><a href="#cb63-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-111"><a href="#cb63-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-112"><a href="#cb63-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-113"><a href="#cb63-113" aria-hidden="true" tabindex="-1"></a>According to a rule of thumb, a VIF &gt; 5 is cause for some concern. A VIF &gt; 10 is definitely problematic. So, we have a problem here. </span>
<span id="cb63-114"><a href="#cb63-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-115"><a href="#cb63-115" aria-hidden="true" tabindex="-1"></a>The above VIF values pertain to variances. I find it more intuitive to discuss the square root of the VIF because they relate to the standard errors.</span>
<span id="cb63-116"><a href="#cb63-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-119"><a href="#cb63-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-120"><a href="#cb63-120" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(car<span class="sc">::</span><span class="fu">vif</span>(mf))</span>
<span id="cb63-121"><a href="#cb63-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-122"><a href="#cb63-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-123"><a href="#cb63-123" aria-hidden="true" tabindex="-1"></a>These $\sqrt{}$VIF values can be interpreted in the following way: the standard error for the effect of <span class="in">`INNERSYS`</span> is around three times larger because of the presence of the other (correlated) variables in the model. The VIF is greatest for <span class="in">`EXTDIA`</span>, which is consistent with this variable seeming to have the highest correlations with the other predictors.  </span>
<span id="cb63-124"><a href="#cb63-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-125"><a href="#cb63-125" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model selection</span></span>
<span id="cb63-126"><a href="#cb63-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-127"><a href="#cb63-127" aria-hidden="true" tabindex="-1"></a>Statisticians use the term "parsimonious" to describe a model that contains no more predictors than necessary to adequately model the data—a model that has the right balance of complexity. </span>
<span id="cb63-128"><a href="#cb63-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-129"><a href="#cb63-129" aria-hidden="true" tabindex="-1"></a>Let’s run a stepwise model selection process to try to find a more parsimonious model than the full model created above. The criterion we will use to assess the quality of the models is Akaike Information Criterion (AIC). Lower AIC values (i.e. closer to $-\infty$) are better.</span>
<span id="cb63-130"><a href="#cb63-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-131"><a href="#cb63-131" aria-hidden="true" tabindex="-1"></a>We will undertake a stepwise process in individual steps, using the <span class="in">`drop1()`</span> function.</span>
<span id="cb63-132"><a href="#cb63-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-135"><a href="#cb63-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-136"><a href="#cb63-136" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mf)</span>
<span id="cb63-137"><a href="#cb63-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-138"><a href="#cb63-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-139"><a href="#cb63-139" aria-hidden="true" tabindex="-1"></a>We have taken the full model (all predictors included) and asked what the AIC values<span class="ot">[^2]</span> would be obtained if we dropped each one of the predictors (or none). The lowest AIC score is for the model with <span class="in">`INNERSYS`</span> removed... so let’s remove it and then use <span class="in">`drop1()`</span> again. </span>
<span id="cb63-140"><a href="#cb63-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-141"><a href="#cb63-141" aria-hidden="true" tabindex="-1"></a><span class="ot">[^2]: </span>Negative values of AIC, as seen here, are uncommon but are nothing to worry about. This occurs when the values of the response variable are small.</span>
<span id="cb63-142"><a href="#cb63-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-145"><a href="#cb63-145" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-146"><a href="#cb63-146" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">update</span>(mf, <span class="sc">~</span> . <span class="sc">-</span> INNERSYS)</span>
<span id="cb63-147"><a href="#cb63-147" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(m2)</span>
<span id="cb63-148"><a href="#cb63-148" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-149"><a href="#cb63-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-150"><a href="#cb63-150" aria-hidden="true" tabindex="-1"></a>Now we remove <span class="in">`OUTERDIA`</span> and repeat.</span>
<span id="cb63-151"><a href="#cb63-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-154"><a href="#cb63-154" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-155"><a href="#cb63-155" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">update</span>(m2, <span class="sc">~</span> . <span class="sc">-</span> OUTERDIA)</span>
<span id="cb63-156"><a href="#cb63-156" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(m3)</span>
<span id="cb63-157"><a href="#cb63-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-158"><a href="#cb63-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-159"><a href="#cb63-159" aria-hidden="true" tabindex="-1"></a>This time, the best model is that with none removed, so the model selection process stops there. Note that this whole process could have been done in a single line of code. </span>
<span id="cb63-160"><a href="#cb63-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-163"><a href="#cb63-163" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-164"><a href="#cb63-164" aria-hidden="true" tabindex="-1"></a>mstep <span class="ot">&lt;-</span> <span class="fu">step</span>(mf)</span>
<span id="cb63-165"><a href="#cb63-165" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-166"><a href="#cb63-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-167"><a href="#cb63-167" aria-hidden="true" tabindex="-1"></a>When you run this, the whole three-step process we executed above will print onscreen and the object <span class="in">`mstep`</span> represents the stepwise-selected model.</span>
<span id="cb63-168"><a href="#cb63-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-169"><a href="#cb63-169" aria-hidden="true" tabindex="-1"></a>Let’s examine the stepwise model.</span>
<span id="cb63-170"><a href="#cb63-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-173"><a href="#cb63-173" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-174"><a href="#cb63-174" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mstep)</span>
<span id="cb63-175"><a href="#cb63-175" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-176"><a href="#cb63-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-177"><a href="#cb63-177" aria-hidden="true" tabindex="-1"></a>We still have two variables that are very highly correlated: <span class="in">`EXTSYS`</span> and <span class="in">`EXTDIA`</span>. Let’s see if this correlation is problematic, according to the VIF criterion.</span>
<span id="cb63-178"><a href="#cb63-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-181"><a href="#cb63-181" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-182"><a href="#cb63-182" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mstep)</span>
<span id="cb63-183"><a href="#cb63-183" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-184"><a href="#cb63-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-185"><a href="#cb63-185" aria-hidden="true" tabindex="-1"></a>With VIF scores for these two variables still well above 5, this is certainly a problem. This illustrates an important point: you must not naively accept a model which results from a stepwise selection process. Always scrutinise a model before accepting it.</span>
<span id="cb63-186"><a href="#cb63-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-187"><a href="#cb63-187" aria-hidden="true" tabindex="-1"></a>We will force a step where we drop either <span class="in">`EXTSYS`</span> or <span class="in">`EXTDIA`</span>.</span>
<span id="cb63-188"><a href="#cb63-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-191"><a href="#cb63-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-192"><a href="#cb63-192" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mstep)</span>
<span id="cb63-193"><a href="#cb63-193" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-194"><a href="#cb63-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-197"><a href="#cb63-197" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-198"><a href="#cb63-198" aria-hidden="true" tabindex="-1"></a>mstep2 <span class="ot">&lt;-</span> <span class="fu">update</span>(mstep,  <span class="sc">~</span> . <span class="sc">-</span> EXTDIA)</span>
<span id="cb63-199"><a href="#cb63-199" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-200"><a href="#cb63-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-201"><a href="#cb63-201" aria-hidden="true" tabindex="-1"></a>Now, let’s try another step.</span>
<span id="cb63-202"><a href="#cb63-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-205"><a href="#cb63-205" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-206"><a href="#cb63-206" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mstep2)</span>
<span id="cb63-207"><a href="#cb63-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-208"><a href="#cb63-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-209"><a href="#cb63-209" aria-hidden="true" tabindex="-1"></a>It seems that the model with <span class="in">`EXTSYS`</span> removed, leaving only <span class="in">`INNERDIA`</span> and <span class="in">`OUTERSYS`</span>, is actually preferable. Once the latter two variables are included, <span class="in">`EXTSYS`</span> does not add any strength to the model. Let’s make this model and check for further removals, and our VIFs.</span>
<span id="cb63-210"><a href="#cb63-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-213"><a href="#cb63-213" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-214"><a href="#cb63-214" aria-hidden="true" tabindex="-1"></a>mstep3 <span class="ot">&lt;-</span> <span class="fu">update</span>(mstep2, <span class="sc">~</span> . <span class="sc">-</span> EXTSYS)</span>
<span id="cb63-215"><a href="#cb63-215" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mstep3)</span>
<span id="cb63-216"><a href="#cb63-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-217"><a href="#cb63-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-220"><a href="#cb63-220" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-221"><a href="#cb63-221" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mstep3)</span>
<span id="cb63-222"><a href="#cb63-222" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-223"><a href="#cb63-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-224"><a href="#cb63-224" aria-hidden="true" tabindex="-1"></a>It seems that this model cannot be improved by dropping any further variables. The variables <span class="in">`INNERDIA`</span> and <span class="in">`OUTERSYS`</span>, though correlated (r = 0.77), do not exert undue influence on each other in the model. </span>
<span id="cb63-225"><a href="#cb63-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-226"><a href="#cb63-226" aria-hidden="true" tabindex="-1"></a>To summarise, let’s see the AIC scores for all the models we’ve made so far.</span>
<span id="cb63-227"><a href="#cb63-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-230"><a href="#cb63-230" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-231"><a href="#cb63-231" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mf, m2, m3, mstep, mstep2, mstep3)</span>
<span id="cb63-232"><a href="#cb63-232" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-233"><a href="#cb63-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-234"><a href="#cb63-234" aria-hidden="true" tabindex="-1"></a>All of these models have very similar AIC. Statisticians say that AIC scores within, say, 3 points can be considered equivalent, and so often we take the approach of choosing the simplest model (i.e. that with the fewest predictors) of all those within 3 AIC points of the lowest score. In some fields it is common to report all models within 10 AIC points or produce an ensemble model bases on AIC weight (not covered in this course). So, while the <span class="in">`mstep3`</span> model isn’t the absolute lowest, it is the simplest model from a bunch of models with roughly equivalent AIC scores. Also, it is a good choice because it doesn’t have the problems with severe multicollinearity found in the other models.</span>
<span id="cb63-235"><a href="#cb63-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-236"><a href="#cb63-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-237"><a href="#cb63-237" aria-hidden="true" tabindex="-1"></a>Don’t worry about the fact that the two functions <span class="in">`drop1()`</span> and <span class="in">`AIC()`</span> give different scores. Remember the AIC is a tool for comparing models—the actual scores don’t matter.  If you look at the difference in AIC scores between two models from the two functions, they are the same. It also should not be compared on models that have different data sources because it is unit less and only acts to compare the models in a specific set.</span>
<span id="cb63-238"><a href="#cb63-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-239"><a href="#cb63-239" aria-hidden="true" tabindex="-1"></a>Difference between AIC scores for <span class="in">`mstep2`</span> and <span class="in">`mstep3`</span> from the <span class="in">`drop1(mstep2)`</span> output:</span>
<span id="cb63-240"><a href="#cb63-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-243"><a href="#cb63-243" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-244"><a href="#cb63-244" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40.395</span> <span class="sc">-</span> (<span class="sc">-</span><span class="fl">42.083</span>)</span>
<span id="cb63-245"><a href="#cb63-245" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-246"><a href="#cb63-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-247"><a href="#cb63-247" aria-hidden="true" tabindex="-1"></a>And from the <span class="in">`AIC(mf, m2, m3, mstep, mstep2, mstep3)`</span> output:</span>
<span id="cb63-248"><a href="#cb63-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-251"><a href="#cb63-251" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-252"><a href="#cb63-252" aria-hidden="true" tabindex="-1"></a><span class="fl">92.14759</span> <span class="sc">-</span> <span class="fl">90.45888</span></span>
<span id="cb63-253"><a href="#cb63-253" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-254"><a href="#cb63-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-255"><a href="#cb63-255" aria-hidden="true" tabindex="-1"></a>So now we can choose <span class="in">`mstep3`</span> and clean up.</span>
<span id="cb63-256"><a href="#cb63-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-259"><a href="#cb63-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-260"><a href="#cb63-260" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(mf, m2, m3, mstep, mstep2) <span class="co"># this code removes these variables</span></span>
<span id="cb63-261"><a href="#cb63-261" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-262"><a href="#cb63-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-263"><a href="#cb63-263" aria-hidden="true" tabindex="-1"></a>Let’s examine the summary for our chosen model. </span>
<span id="cb63-264"><a href="#cb63-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-267"><a href="#cb63-267" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-268"><a href="#cb63-268" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mstep3)</span>
<span id="cb63-269"><a href="#cb63-269" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-270"><a href="#cb63-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-271"><a href="#cb63-271" aria-hidden="true" tabindex="-1"></a>We are now explaining 72% of the variation in heart weights with two variables, as opposed to 75% of the variation with six variables in the original full model. Note also that, in the full model, <span class="in">`INNERDIA`</span> was not significant and <span class="in">`OUTERSYS`</span> was only weakly significant. In the smaller model, both these predictors were highly significant. Personally, I would definitely prefer the more parsimonious two-variable model, especially if it meant that I had only to take two, rather than six, ultrasound measurements on a thousand horses! </span>
<span id="cb63-272"><a href="#cb63-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-273"><a href="#cb63-273" aria-hidden="true" tabindex="-1"></a>But we’re not done yet. We must use some diagnostic tools to examine whether our model meets the assumptions of linear regression before we can accept it.</span>
<span id="cb63-274"><a href="#cb63-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-275"><a href="#cb63-275" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model diagnostics</span></span>
<span id="cb63-276"><a href="#cb63-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-277"><a href="#cb63-277" aria-hidden="true" tabindex="-1"></a>Examine the usual four diagnostic plots.</span>
<span id="cb63-278"><a href="#cb63-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-281"><a href="#cb63-281" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-282"><a href="#cb63-282" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mstep3)</span>
<span id="cb63-283"><a href="#cb63-283" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-284"><a href="#cb63-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-285"><a href="#cb63-285" aria-hidden="true" tabindex="-1"></a>The Residuals-vs-Fitted plot shows a slight decreasing trend in the residuals at low fitted values, but it is only a few points. It might pay, though, to bear in mind that the model is likely to overestimate lower heart weights.</span>
<span id="cb63-286"><a href="#cb63-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-287"><a href="#cb63-287" aria-hidden="true" tabindex="-1"></a>The normal Q-Q plot is not too worrying, although there are a few higher-than-expected residuals. </span>
<span id="cb63-288"><a href="#cb63-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-289"><a href="#cb63-289" aria-hidden="true" tabindex="-1"></a>The Scale-Location plot shows no strong evidence of heteroscedasticity—the variance appears fairly constant across fitted values. </span>
<span id="cb63-290"><a href="#cb63-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-291"><a href="#cb63-291" aria-hidden="true" tabindex="-1"></a>And, finally, there are no very large values of Cook’s distance or leverage.</span>
<span id="cb63-292"><a href="#cb63-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-293"><a href="#cb63-293" aria-hidden="true" tabindex="-1"></a>There are many other diagnostic tools and graphs available, many in the <span class="in">`car`</span> library, which we do not have time to go into here. If you’re interested, this website is a good place to start: <span class="ot">&lt;http://www.statmethods.net/stats/rdiagnostics.html&gt;</span>.</span>
<span id="cb63-294"><a href="#cb63-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-295"><a href="#cb63-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-296"><a href="#cb63-296" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3D plots</span></span>
<span id="cb63-297"><a href="#cb63-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-298"><a href="#cb63-298" aria-hidden="true" tabindex="-1"></a>Since there are three variables involved in this model, it might be useful to examine their relationship using 3D plots. We can include the 2D plane that represents our regression model on the plot, using the following code.</span>
<span id="cb63-299"><a href="#cb63-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-302"><a href="#cb63-302" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-303"><a href="#cb63-303" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scatterplot3d)</span>
<span id="cb63-304"><a href="#cb63-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-305"><a href="#cb63-305" aria-hidden="true" tabindex="-1"></a>hh3d <span class="ot">&lt;-</span> <span class="fu">scatterplot3d</span>(</span>
<span id="cb63-306"><a href="#cb63-306" aria-hidden="true" tabindex="-1"></a>  hh<span class="sc">$</span>INNERDIA, </span>
<span id="cb63-307"><a href="#cb63-307" aria-hidden="true" tabindex="-1"></a>  hh<span class="sc">$</span>OUTERSYS, </span>
<span id="cb63-308"><a href="#cb63-308" aria-hidden="true" tabindex="-1"></a>  hh<span class="sc">$</span>WEIGHT,</span>
<span id="cb63-309"><a href="#cb63-309" aria-hidden="true" tabindex="-1"></a>  <span class="at">type=</span><span class="st">"h"</span>, </span>
<span id="cb63-310"><a href="#cb63-310" aria-hidden="true" tabindex="-1"></a>  <span class="at">highlight.3d=</span>T,</span>
<span id="cb63-311"><a href="#cb63-311" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">16</span></span>
<span id="cb63-312"><a href="#cb63-312" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb63-313"><a href="#cb63-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-314"><a href="#cb63-314" aria-hidden="true" tabindex="-1"></a>hh3d<span class="sc">$</span><span class="fu">plane3d</span>(mstep3)</span>
<span id="cb63-315"><a href="#cb63-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-316"><a href="#cb63-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-317"><a href="#cb63-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-318"><a href="#cb63-318" aria-hidden="true" tabindex="-1"></a>Finally, use <span class="in">`plotly`</span> to create a dynamic 3D plot which you can rotate using your mouse. Don’t say I never treat you!</span>
<span id="cb63-319"><a href="#cb63-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-322"><a href="#cb63-322" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-323"><a href="#cb63-323" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb63-324"><a href="#cb63-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-325"><a href="#cb63-325" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_ly</span>(</span>
<span id="cb63-326"><a href="#cb63-326" aria-hidden="true" tabindex="-1"></a>  hh, </span>
<span id="cb63-327"><a href="#cb63-327" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="sc">~</span>INNERDIA, </span>
<span id="cb63-328"><a href="#cb63-328" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="sc">~</span>OUTERDIA, </span>
<span id="cb63-329"><a href="#cb63-329" aria-hidden="true" tabindex="-1"></a>  <span class="at">z =</span> <span class="sc">~</span>WEIGHT</span>
<span id="cb63-330"><a href="#cb63-330" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb63-331"><a href="#cb63-331" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_markers</span>()</span>
<span id="cb63-332"><a href="#cb63-332" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-333"><a href="#cb63-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-334"><a href="#cb63-334" aria-hidden="true" tabindex="-1"></a>I do not recommend 3-D plots for print reports/publications. They are often best viewed interactively. Instead try using colors or bubbles for continuous third variables and shapes or facets for discrete third variables.</span>
<span id="cb63-335"><a href="#cb63-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-336"><a href="#cb63-336" aria-hidden="true" tabindex="-1"></a>For example:</span>
<span id="cb63-337"><a href="#cb63-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-340"><a href="#cb63-340" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-341"><a href="#cb63-341" aria-hidden="true" tabindex="-1"></a>hh <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span>OUTERDIA, <span class="at">x=</span>INNERDIA, <span class="at">color=</span>WEIGHT))<span class="sc">+</span></span>
<span id="cb63-342"><a href="#cb63-342" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span>
<span id="cb63-343"><a href="#cb63-343" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-344"><a href="#cb63-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-345"><a href="#cb63-345" aria-hidden="true" tabindex="-1"></a><span class="fu"># Dataset **`Prestige`**</span></span>
<span id="cb63-346"><a href="#cb63-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-347"><a href="#cb63-347" aria-hidden="true" tabindex="-1"></a>We will continue to use dataset <span class="in">`Prestige`</span> from the <span class="in">`car`</span>   R package. </span>
<span id="cb63-348"><a href="#cb63-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-349"><a href="#cb63-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-350"><a href="#cb63-350" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercise 7.1 {-}</span></span>
<span id="cb63-351"><a href="#cb63-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-352"><a href="#cb63-352" aria-hidden="true" tabindex="-1"></a>Obtain the matrix plot of the numerical variables <span class="in">`education`</span>, <span class="in">`income`</span>, <span class="in">`women`</span>, and <span class="in">`prestige`</span>.</span>
<span id="cb63-353"><a href="#cb63-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-354"><a href="#cb63-354" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, fig.show='hide'}</span></span>
<span id="cb63-355"><a href="#cb63-355" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb63-356"><a href="#cb63-356" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb63-357"><a href="#cb63-357" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb63-358"><a href="#cb63-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-359"><a href="#cb63-359" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-360"><a href="#cb63-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-361"><a href="#cb63-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-362"><a href="#cb63-362" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, fig.show='hide'}</span></span>
<span id="cb63-363"><a href="#cb63-363" aria-hidden="true" tabindex="-1"></a>Prestige <span class="sc">|&gt;</span> </span>
<span id="cb63-364"><a href="#cb63-364" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(prestige, education, income, women) <span class="sc">|&gt;</span> </span>
<span id="cb63-365"><a href="#cb63-365" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggpairs</span>(<span class="fu">aes</span>(<span class="at">colour=</span>Prestige<span class="sc">$</span>type))</span>
<span id="cb63-366"><a href="#cb63-366" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-367"><a href="#cb63-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-368"><a href="#cb63-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-369"><a href="#cb63-369" aria-hidden="true" tabindex="-1"></a>Obtain their correlation matrix.</span>
<span id="cb63-370"><a href="#cb63-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-371"><a href="#cb63-371" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, fig.show='hide', results='hide'}</span></span>
<span id="cb63-372"><a href="#cb63-372" aria-hidden="true" tabindex="-1"></a><span class="co"># Old style pairs plot</span></span>
<span id="cb63-373"><a href="#cb63-373" aria-hidden="true" tabindex="-1"></a>Prestige <span class="sc">|&gt;</span> </span>
<span id="cb63-374"><a href="#cb63-374" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(prestige, education, income, women) <span class="sc">|&gt;</span></span>
<span id="cb63-375"><a href="#cb63-375" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>()</span>
<span id="cb63-376"><a href="#cb63-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-377"><a href="#cb63-377" aria-hidden="true" tabindex="-1"></a>Prestige <span class="sc">|&gt;</span> </span>
<span id="cb63-378"><a href="#cb63-378" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(prestige, education, income, women) <span class="sc">|&gt;</span></span>
<span id="cb63-379"><a href="#cb63-379" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span>
<span id="cb63-380"><a href="#cb63-380" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-381"><a href="#cb63-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-382"><a href="#cb63-382" aria-hidden="true" tabindex="-1"></a>Fit a (full) multiple regression of  <span class="in">`prestige`</span> on <span class="in">`education`</span>, <span class="in">`income`</span>, &amp; <span class="in">`women`</span>. </span>
<span id="cb63-383"><a href="#cb63-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-384"><a href="#cb63-384" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='hide'}</span></span>
<span id="cb63-385"><a href="#cb63-385" aria-hidden="true" tabindex="-1"></a>full.reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> income <span class="sc">+</span> women,</span>
<span id="cb63-386"><a href="#cb63-386" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> Prestige)</span>
<span id="cb63-387"><a href="#cb63-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-388"><a href="#cb63-388" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-389"><a href="#cb63-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-390"><a href="#cb63-390" aria-hidden="true" tabindex="-1"></a>Obtain the plots for residual diagnostics.</span>
<span id="cb63-391"><a href="#cb63-391" aria-hidden="true" tabindex="-1"></a>Residual plots</span>
<span id="cb63-392"><a href="#cb63-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-393"><a href="#cb63-393" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, fig.show='hide'}</span></span>
<span id="cb63-394"><a href="#cb63-394" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb63-395"><a href="#cb63-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-396"><a href="#cb63-396" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(full.reg, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb63-397"><a href="#cb63-397" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-398"><a href="#cb63-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-399"><a href="#cb63-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-400"><a href="#cb63-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-401"><a href="#cb63-401" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, fig.show='hide'}</span></span>
<span id="cb63-402"><a href="#cb63-402" aria-hidden="true" tabindex="-1"></a><span class="co"># Old style plots</span></span>
<span id="cb63-403"><a href="#cb63-403" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(full.reg, <span class="dv">1</span>) <span class="co"># the argument 1 can be changed up to 6</span></span>
<span id="cb63-404"><a href="#cb63-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-405"><a href="#cb63-405" aria-hidden="true" tabindex="-1"></a><span class="co"># or just use</span></span>
<span id="cb63-406"><a href="#cb63-406" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb63-407"><a href="#cb63-407" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(full.reg)</span>
<span id="cb63-408"><a href="#cb63-408" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-409"><a href="#cb63-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-410"><a href="#cb63-410" aria-hidden="true" tabindex="-1"></a>Regression outputs</span>
<span id="cb63-411"><a href="#cb63-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-414"><a href="#cb63-414" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-415"><a href="#cb63-415" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full.reg)</span>
<span id="cb63-416"><a href="#cb63-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-417"><a href="#cb63-417" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(full.reg)</span>
<span id="cb63-418"><a href="#cb63-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-419"><a href="#cb63-419" aria-hidden="true" tabindex="-1"></a><span class="fu">extractAIC</span>(full.reg)</span>
<span id="cb63-420"><a href="#cb63-420" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-421"><a href="#cb63-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-422"><a href="#cb63-422" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercise 7.2 {-}</span></span>
<span id="cb63-423"><a href="#cb63-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-424"><a href="#cb63-424" aria-hidden="true" tabindex="-1"></a>Perform stepwise regression analysis of <span class="in">`prestige`</span> on <span class="in">`education`</span>, <span class="in">`income`</span>, &amp; <span class="in">`women`</span>. </span>
<span id="cb63-425"><a href="#cb63-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-426"><a href="#cb63-426" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='hide'}</span></span>
<span id="cb63-427"><a href="#cb63-427" aria-hidden="true" tabindex="-1"></a>full.reg <span class="ot">=</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> income <span class="sc">+</span> women,</span>
<span id="cb63-428"><a href="#cb63-428" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> Prestige)</span>
<span id="cb63-429"><a href="#cb63-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-430"><a href="#cb63-430" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(full.reg)</span>
<span id="cb63-431"><a href="#cb63-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-432"><a href="#cb63-432" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(full.reg, <span class="at">direction=</span><span class="st">"backward"</span>)</span>
<span id="cb63-433"><a href="#cb63-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-434"><a href="#cb63-434" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(full.reg, <span class="at">direction=</span><span class="st">"both"</span>)</span>
<span id="cb63-435"><a href="#cb63-435" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-436"><a href="#cb63-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-437"><a href="#cb63-437" aria-hidden="true" tabindex="-1"></a>The function <span class="in">`update()`</span> is handy for making adjustments to a model. For example, see try the following codes:</span>
<span id="cb63-438"><a href="#cb63-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-439"><a href="#cb63-439" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='hide'}</span></span>
<span id="cb63-440"><a href="#cb63-440" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">=</span> <span class="fu">update</span>(full.reg,  . <span class="sc">~</span> . <span class="sc">-</span> women)</span>
<span id="cb63-441"><a href="#cb63-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-442"><a href="#cb63-442" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span>
<span id="cb63-443"><a href="#cb63-443" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-444"><a href="#cb63-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-445"><a href="#cb63-445" aria-hidden="true" tabindex="-1"></a>Note that <span class="in">` . ~ . - women`</span> means that the model is fitted without the <span class="in">`women`</span> variable.</span>
<span id="cb63-446"><a href="#cb63-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-447"><a href="#cb63-447" aria-hidden="true" tabindex="-1"></a>Further options are available in <span class="in">`leaps`</span> and <span class="in">`HH`</span> packages </span>
<span id="cb63-448"><a href="#cb63-448" aria-hidden="true" tabindex="-1"></a>(installation commands are given below).</span>
<span id="cb63-449"><a href="#cb63-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-450"><a href="#cb63-450" aria-hidden="true" tabindex="-1"></a><span class="in">`install.packages("leaps", repos = "https://cran.r-project.org")`</span></span>
<span id="cb63-451"><a href="#cb63-451" aria-hidden="true" tabindex="-1"></a><span class="in">`install.packages("HH", repos = "https://cran.r-project.org")`</span></span>
<span id="cb63-452"><a href="#cb63-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-453"><a href="#cb63-453" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='hide', fig.show='hide'}</span></span>
<span id="cb63-454"><a href="#cb63-454" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb63-455"><a href="#cb63-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-456"><a href="#cb63-456" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">regsubsets</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> income <span class="sc">+</span> women, </span>
<span id="cb63-457"><a href="#cb63-457" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> Prestige)</span>
<span id="cb63-458"><a href="#cb63-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-459"><a href="#cb63-459" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HH)</span>
<span id="cb63-460"><a href="#cb63-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-461"><a href="#cb63-461" aria-hidden="true" tabindex="-1"></a><span class="fu">summaryHH</span>(model)</span>
<span id="cb63-462"><a href="#cb63-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-463"><a href="#cb63-463" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">summaryHH</span>(model))</span>
<span id="cb63-464"><a href="#cb63-464" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-465"><a href="#cb63-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-466"><a href="#cb63-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-467"><a href="#cb63-467" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercise 7.3 {-}</span></span>
<span id="cb63-468"><a href="#cb63-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-469"><a href="#cb63-469" aria-hidden="true" tabindex="-1"></a>Perform a polynomial regression of <span class="in">`prestige`</span> on <span class="in">`income`</span>. </span>
<span id="cb63-470"><a href="#cb63-470" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-471"><a href="#cb63-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-472"><a href="#cb63-472" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='hide', fig.show='hide'}</span></span>
<span id="cb63-473"><a href="#cb63-473" aria-hidden="true" tabindex="-1"></a><span class="co"># Cubic fit</span></span>
<span id="cb63-474"><a href="#cb63-474" aria-hidden="true" tabindex="-1"></a>p.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> <span class="fu">poly</span>(income,<span class="dv">3</span>),</span>
<span id="cb63-475"><a href="#cb63-475" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> Prestige)</span>
<span id="cb63-476"><a href="#cb63-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-477"><a href="#cb63-477" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(p.model)</span>
<span id="cb63-478"><a href="#cb63-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-479"><a href="#cb63-479" aria-hidden="true" tabindex="-1"></a><span class="fu">extractAIC</span>(p.model)</span>
<span id="cb63-480"><a href="#cb63-480" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-481"><a href="#cb63-481" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p.model)</span>
<span id="cb63-482"><a href="#cb63-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-483"><a href="#cb63-483" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(p.model)</span>
<span id="cb63-484"><a href="#cb63-484" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-485"><a href="#cb63-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-486"><a href="#cb63-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-487"><a href="#cb63-487" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>More R code examples are <span class="co">[</span><span class="ot">here</span><span class="co">](../exercises/Chap7more.R)</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>